SET PAGESIZE 1000
SET LINESIZE 250
SET FEEDBACK ON
SET HEADING ON

PROMPT ========================================
PROMPT Analyzing All OPERATION-Related Tables
PROMPT ========================================

-- Count records in each OPERATION table
PROMPT
PROMPT Record counts for all OPERATION tables:
PROMPT

SELECT 'OPERATION_' as TABLE_NAME, COUNT(*) as RECORD_COUNT
FROM DESIGN12.OPERATION_
UNION ALL
SELECT 'OPERATION_EX_' as TABLE_NAME, COUNT(*) as RECORD_COUNT
FROM DESIGN12.OPERATION_EX_
UNION ALL
SELECT 'OPERATIONINSTANCE_' as TABLE_NAME, COUNT(*) as RECORD_COUNT
FROM DESIGN12.OPERATIONINSTANCE_
UNION ALL
SELECT 'OPERATIONINSTANCE_EX_' as TABLE_NAME, COUNT(*) as RECORD_COUNT
FROM DESIGN12.OPERATIONINSTANCE_EX_
UNION ALL
SELECT 'OPERATIONROUTE_' as TABLE_NAME, COUNT(*) as RECORD_COUNT
FROM DESIGN12.OPERATIONROUTE_
UNION ALL
SELECT 'OPERATIONROUTE_EX_' as TABLE_NAME, COUNT(*) as RECORD_COUNT
FROM DESIGN12.OPERATIONROUTE_EX_
UNION ALL
SELECT 'OPERATIONWIASPECT_' as TABLE_NAME, COUNT(*) as RECORD_COUNT
FROM DESIGN12.OPERATIONWIASPECT_
UNION ALL
SELECT 'OPERATIONWIASPECT_EX_' as TABLE_NAME, COUNT(*) as RECORD_COUNT
FROM DESIGN12.OPERATIONWIASPECT_EX_
ORDER BY TABLE_NAME;

PROMPT
PROMPT ========================================
PROMPT Sample from OPERATION_ table
PROMPT ========================================

SELECT
    op.OBJECT_ID,
    op.NAME_S_,
    op.CAPTION_S_,
    op.CLASS_ID,
    cd.NAME as CLASS_NAME,
    cd.NICE_NAME,
    cd.TYPE_ID
FROM DESIGN12.OPERATION_ op
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON op.CLASS_ID = cd.TYPE_ID
WHERE ROWNUM <= 10
ORDER BY op.OBJECT_ID;

PROMPT
PROMPT ========================================
PROMPT Check parent relationships for OPERATION_
PROMPT ========================================

SELECT
    COUNT(*) as TOTAL_OPERATIONS,
    COUNT(rc.OBJECT_ID) as WITH_REL_COMMON,
    COUNT(rc.FORWARD_OBJECT_ID) as WITH_PARENT,
    COUNT(CASE WHEN c.OBJECT_ID IS NOT NULL THEN 1 END) as PARENT_IS_COLLECTION,
    COUNT(CASE WHEN op2.OBJECT_ID IS NOT NULL THEN 1 END) as PARENT_IS_OPERATION
FROM DESIGN12.OPERATION_ op
LEFT JOIN DESIGN12.REL_COMMON rc ON op.OBJECT_ID = rc.OBJECT_ID
LEFT JOIN DESIGN12.COLLECTION_ c ON rc.FORWARD_OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.OPERATION_ op2 ON rc.FORWARD_OBJECT_ID = op2.OBJECT_ID;

PROMPT
PROMPT ========================================
PROMPT Check CLASS_DEFINITIONS for operation types
PROMPT ========================================

SELECT
    cd.TYPE_ID,
    cd.NAME,
    cd.NICE_NAME,
    cd.HARD_TABLE_NAME,
    cd.DERIVED_FROM
FROM DESIGN12.CLASS_DEFINITIONS cd
WHERE cd.HARD_TABLE_NAME LIKE 'OPERATION%'
ORDER BY cd.TYPE_ID;

PROMPT
PROMPT ========================================
PROMPT Sample operations under FORD_DEARBORN project
PROMPT ========================================

-- Find operations whose names match those from your screenshots
SELECT
    op.OBJECT_ID,
    op.NAME_S_,
    op.CAPTION_S_,
    cd.NAME as CLASS_NAME,
    cd.TYPE_ID,
    rc.FORWARD_OBJECT_ID as PARENT_ID
FROM DESIGN12.OPERATION_ op
INNER JOIN DESIGN12.REL_COMMON rc ON op.OBJECT_ID = rc.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON op.CLASS_ID = cd.TYPE_ID
WHERE op.NAME_S_ IN ('MOV_HOME', 'COMM_PICK01', 'COMM_PICK02', 'PROGRAM_DATA', 'SITE_BACKUP')
AND ROWNUM <= 10
ORDER BY op.NAME_S_;

EXIT;
