SET PAGESIZE 100
SET LINESIZE 250
SET FEEDBACK ON

PROMPT Finding COMM_PICK01 operation and its ancestry...

-- Find COMM_PICK01 and trace up to project root
SELECT
    LEVEL as LVL,
    LPAD(' ', (LEVEL-1)*2) || NVL(c.CAPTION_S_, op.NAME_S_) as TREE_PATH,
    rc.OBJECT_ID,
    rc.FORWARD_OBJECT_ID as PARENT_ID,
    CASE
        WHEN c.OBJECT_ID IS NOT NULL THEN 'COLLECTION_'
        WHEN op2.OBJECT_ID IS NOT NULL THEN 'OPERATION_'
        ELSE 'UNKNOWN'
    END as OBJECT_TYPE
FROM DESIGN12.REL_COMMON rc
LEFT JOIN DESIGN12.COLLECTION_ c ON rc.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.OPERATION_ op ON rc.OBJECT_ID = op.OBJECT_ID
LEFT JOIN DESIGN12.OPERATION_ op2 ON rc.FORWARD_OBJECT_ID = op2.OBJECT_ID
START WITH rc.OBJECT_ID = (
    SELECT op3.OBJECT_ID
    FROM DESIGN12.OPERATION_ op3
    WHERE op3.NAME_S_ = 'COMM_PICK01'
    AND ROWNUM = 1
)
CONNECT BY NOCYCLE PRIOR rc.FORWARD_OBJECT_ID = rc.OBJECT_ID;

EXIT;
