-- COMPREHENSIVE DEBUG: All three issues with proof of work
-- Issue 1: EngineeringResourceLibrary icon (18153685)
-- Issue 2: COWL_SILL_SIDE missing children (18208744)
-- Issue 3: PartInstanceLibrary missing children (18143953)

SET LINESIZE 200
SET PAGESIZE 50000
SET FEEDBACK ON

PROMPT ======================================================================
PROMPT ISSUE 1: EngineeringResourceLibrary (18153685) Icon Debug
PROMPT ======================================================================
PROMPT
PROMPT 1A. EngineeringResourceLibrary node details:

SELECT
    c.OBJECT_ID,
    c.CAPTION_S_ as CAPTION,
    c.CLASS_ID,
    cd.NAME as CLASS_NAME,
    cd.NICE_NAME,
    cd.TYPE_ID
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE c.OBJECT_ID = 18153685;

PROMPT
PROMPT 1B. What are the parent relationships?

SELECT
    r.FORWARD_OBJECT_ID as PARENT_ID,
    parent.CAPTION_S_ as PARENT_CAPTION,
    parent_cd.NICE_NAME as PARENT_NICE_NAME,
    parent_cd.TYPE_ID as PARENT_TYPE_ID
FROM DESIGN12.REL_COMMON r
INNER JOIN DESIGN12.COLLECTION_ parent ON r.FORWARD_OBJECT_ID = parent.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS parent_cd ON parent.CLASS_ID = parent_cd.TYPE_ID
WHERE r.OBJECT_ID = 18153685;

PROMPT
PROMPT 1C. Comparison - ResourceLibrary vs EngineeringResourceLibrary TYPE_IDs:

SELECT DISTINCT TYPE_ID, NICE_NAME, NAME
FROM DESIGN12.CLASS_DEFINITIONS
WHERE NICE_NAME IN ('ResourceLibrary', 'EngineeringResourceLibrary')
ORDER BY NICE_NAME;

PROMPT
PROMPT 1D. Do these TYPE_IDs have icons in DF_ICONS_DATA?

SELECT di.TYPE_ID,
    CASE WHEN di.CLASS_IMAGE IS NULL THEN 'NO' ELSE 'YES' END as HAS_ICON,
    DBMS_LOB.GETLENGTH(di.CLASS_IMAGE) as ICON_SIZE
FROM DESIGN12.DF_ICONS_DATA di
WHERE di.TYPE_ID IN (
    SELECT TYPE_ID FROM DESIGN12.CLASS_DEFINITIONS
    WHERE NICE_NAME IN ('ResourceLibrary', 'EngineeringResourceLibrary')
)
ORDER BY di.TYPE_ID;

PROMPT
PROMPT ======================================================================
PROMPT ISSUE 2: COWL_SILL_SIDE (18208744) Missing Children
PROMPT ======================================================================
PROMPT
PROMPT 2A. COWL_SILL_SIDE node details:

SELECT
    c.OBJECT_ID,
    c.CAPTION_S_ as CAPTION,
    c.CLASS_ID,
    cd.NAME as CLASS_NAME,
    cd.NICE_NAME,
    cd.TYPE_ID
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE c.OBJECT_ID = 18208744;

PROMPT
PROMPT 2B. Direct children of COWL_SILL_SIDE via REL_COMMON:

SELECT
    r.OBJECT_ID as CHILD_ID,
    c.CAPTION_S_ as CHILD_CAPTION,
    cd.NICE_NAME as CHILD_NICE_NAME,
    cd.TYPE_ID as CHILD_TYPE_ID
FROM DESIGN12.REL_COMMON r
INNER JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18208744
ORDER BY c.CAPTION_S_;

PROMPT
PROMPT 2C. Count by type:

SELECT
    cd.NICE_NAME,
    cd.TYPE_ID,
    COUNT(*) as COUNT
FROM DESIGN12.REL_COMMON r
INNER JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18208744
GROUP BY cd.NICE_NAME, cd.TYPE_ID
ORDER BY COUNT DESC;

PROMPT
PROMPT 2D. Does COWL_SILL_SIDE exist in PART_ table?

SELECT
    p.OBJECT_ID,
    p.NAME_S_ as PART_NAME,
    p.CLASS_ID,
    cd.NICE_NAME
FROM DESIGN12.PART_ p
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON p.CLASS_ID = cd.TYPE_ID
WHERE p.OBJECT_ID = 18208744;

PROMPT
PROMPT 2E. Children in PART_ table under COWL_SILL_SIDE (via REL_COMMON):

SELECT
    r.OBJECT_ID as CHILD_ID,
    p.NAME_S_ as CHILD_NAME,
    cd.NICE_NAME as CHILD_NICE_NAME,
    cd.TYPE_ID as CHILD_TYPE_ID
FROM DESIGN12.REL_COMMON r
INNER JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON p.CLASS_ID = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18208744
ORDER BY p.NAME_S_;

PROMPT
PROMPT ======================================================================
PROMPT ISSUE 3: PartInstanceLibrary (18143953) Missing Children
PROMPT ======================================================================
PROMPT
PROMPT 3A. PartInstanceLibrary node details:

SELECT
    c.OBJECT_ID,
    c.CAPTION_S_ as CAPTION,
    c.CLASS_ID,
    cd.NAME as CLASS_NAME,
    cd.NICE_NAME,
    cd.TYPE_ID
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE c.OBJECT_ID = 18143953;

PROMPT
PROMPT 3B. Direct children of PartInstanceLibrary via REL_COMMON (COLLECTION_ table):

SELECT
    r.OBJECT_ID as CHILD_ID,
    c.CAPTION_S_ as CHILD_CAPTION,
    cd.NICE_NAME as CHILD_NICE_NAME,
    cd.TYPE_ID as CHILD_TYPE_ID
FROM DESIGN12.REL_COMMON r
INNER JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18143953
ORDER BY cd.NICE_NAME, c.CAPTION_S_;

PROMPT
PROMPT 3C. Children in PART_ table under PartInstanceLibrary:

SELECT
    r.OBJECT_ID as CHILD_ID,
    p.NAME_S_ as CHILD_NAME,
    cd.NICE_NAME as CHILD_NICE_NAME,
    cd.TYPE_ID as CHILD_TYPE_ID
FROM DESIGN12.REL_COMMON r
INNER JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON p.CLASS_ID = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18143953
ORDER BY cd.NICE_NAME, p.NAME_S_;

PROMPT
PROMPT 3D. Count by type (PART_ children):

SELECT
    cd.NICE_NAME,
    cd.TYPE_ID,
    COUNT(*) as COUNT
FROM DESIGN12.REL_COMMON r
INNER JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON p.CLASS_ID = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18143953
GROUP BY cd.NICE_NAME, cd.TYPE_ID
ORDER BY COUNT DESC;

EXIT
