-- Deeper investigation
SET LINESIZE 200
SET PAGESIZE 50000

PROMPT ======================================================================
PROMPT ISSUE 1 DEEPER: Why is EngineeringResourceLibrary using TYPE_ID 164?
PROMPT ======================================================================
PROMPT
PROMPT 1. All TYPE_IDs in range 160-170:

SELECT TYPE_ID, NICE_NAME, NAME
FROM DESIGN12.CLASS_DEFINITIONS
WHERE TYPE_ID BETWEEN 160 AND 170
ORDER BY TYPE_ID;

PROMPT
PROMPT 2. Does TYPE_ID 164 have icon data?

SELECT TYPE_ID,
    CASE WHEN CLASS_IMAGE IS NULL THEN 'NO' ELSE 'YES' END as HAS_ICON,
    DBMS_LOB.GETLENGTH(CLASS_IMAGE) as ICON_SIZE
FROM DESIGN12.DF_ICONS_DATA
WHERE TYPE_ID = 164;

PROMPT
PROMPT 3. What TYPE_IDs have icons for Resource-related types?

SELECT di.TYPE_ID,
    CASE WHEN di.CLASS_IMAGE IS NULL THEN 'NO' ELSE 'YES' END as HAS_ICON,
    DBMS_LOB.GETLENGTH(di.CLASS_IMAGE) as ICON_SIZE
FROM DESIGN12.DF_ICONS_DATA di
WHERE di.TYPE_ID IN (
    SELECT TYPE_ID FROM DESIGN12.CLASS_DEFINITIONS
    WHERE NICE_NAME LIKE '%Resource%'
)
ORDER BY di.TYPE_ID;

PROMPT
PROMPT ======================================================================
PROMPT ISSUE 2 DEEPER: Where are COWL_SILL_SIDE's PartPrototype children?
PROMPT ======================================================================
PROMPT
PROMPT 1. ALL children of COWL_SILL_SIDE across ALL tables:

SELECT 'COLLECTION' as SOURCE,
    r.OBJECT_ID as CHILD_ID,
    c.CAPTION_S_ as CHILD_NAME,
    cd.NICE_NAME as CHILD_TYPE
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18208744
UNION ALL
SELECT 'PART' as SOURCE,
    r.OBJECT_ID as CHILD_ID,
    p.NAME_S_ as CHILD_NAME,
    cd.NICE_NAME as CHILD_TYPE
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON p.CLASS_ID = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18208744
ORDER BY SOURCE, CHILD_NAME;

PROMPT
PROMPT 2. Recursive children of COWL_SILL_SIDE (2 levels deep):

SELECT LEVEL, r.OBJECT_ID, r.FORWARD_OBJECT_ID,
    NVL(c.CAPTION_S_, p.NAME_S_) as NODE_NAME,
    cd.NICE_NAME as NODE_TYPE
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON NVL(c.CLASS_ID, p.CLASS_ID) = cd.TYPE_ID
START WITH r.FORWARD_OBJECT_ID = 18208744
CONNECT BY PRIOR r.OBJECT_ID = r.FORWARD_OBJECT_ID
    AND LEVEL <= 2;

PROMPT
PROMPT ======================================================================
PROMPT ISSUE 3 DEEPER: PartInstanceLibrary investigation
PROMPT ======================================================================
PROMPT
PROMPT 1. Does 18143953 exist in PART_ table?

SELECT p.OBJECT_ID, p.NAME_S_, p.CLASS_ID, cd.NICE_NAME
FROM DESIGN12.PART_ p
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON p.CLASS_ID = cd.TYPE_ID
WHERE p.OBJECT_ID = 18143953;

PROMPT
PROMPT 2. Find ALL PartInstanceLibrary nodes:

SELECT c.OBJECT_ID, c.CAPTION_S_, cd.TYPE_ID, cd.NICE_NAME
FROM DESIGN12.COLLECTION_ c
INNER JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE cd.NICE_NAME = 'PartInstanceLibrary';

PROMPT
PROMPT 3. ALL children of ANY PartInstanceLibrary (if it exists):

SELECT
    pil.OBJECT_ID as PIL_ID,
    pil.CAPTION_S_ as PIL_NAME,
    r.OBJECT_ID as CHILD_ID,
    NVL(c.CAPTION_S_, p.NAME_S_) as CHILD_NAME,
    cd.NICE_NAME as CHILD_TYPE
FROM DESIGN12.COLLECTION_ pil
INNER JOIN DESIGN12.CLASS_DEFINITIONS pil_cd ON pil.CLASS_ID = pil_cd.TYPE_ID
INNER JOIN DESIGN12.REL_COMMON r ON r.FORWARD_OBJECT_ID = pil.OBJECT_ID
LEFT JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON NVL(c.CLASS_ID, p.CLASS_ID) = cd.TYPE_ID
WHERE pil_cd.NICE_NAME = 'PartInstanceLibrary'
ORDER BY pil.OBJECT_ID, cd.NICE_NAME, CHILD_NAME;

EXIT
