SET PAGESIZE 100
SET LINESIZE 400
SET FEEDBACK OFF
SET HEADING ON

PROMPT === Check COWL_SILL_SIDE [18208744] location ===
SELECT 'COLLECTION_' AS TABLE_NAME FROM DESIGN12.COLLECTION_ WHERE OBJECT_ID = 18208744
UNION ALL
SELECT 'PART_' AS TABLE_NAME FROM DESIGN12.PART_ WHERE OBJECT_ID = 18208744;

PROMPT
PROMPT === Check children of COWL_SILL_SIDE in REL_COMMON ===
SELECT
    r.OBJECT_ID,
    r.SEQ_NUMBER,
    CASE
        WHEN c.OBJECT_ID IS NOT NULL THEN 'COLLECTION_'
        WHEN p.OBJECT_ID IS NOT NULL THEN 'PART_'
        ELSE 'NEITHER'
    END AS CHILD_TABLE,
    COALESCE(c.CAPTION_S_, p.NAME_S_, 'Unknown') AS NAME,
    cd.NICE_NAME AS TYPE
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON COALESCE(c.CLASS_ID, p.CLASS_ID) = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18208744
ORDER BY r.SEQ_NUMBER;

PROMPT
PROMPT === Check parent of COWL_SILL_SIDE (CC node) ===
SELECT
    r.FORWARD_OBJECT_ID AS PARENT_ID,
    CASE
        WHEN c.OBJECT_ID IS NOT NULL THEN 'COLLECTION_'
        WHEN p.OBJECT_ID IS NOT NULL THEN 'PART_'
        ELSE 'NEITHER'
    END AS PARENT_TABLE,
    COALESCE(c.CAPTION_S_, p.NAME_S_, 'Unknown') AS PARENT_NAME,
    cd.NICE_NAME AS PARENT_TYPE
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.FORWARD_OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.PART_ p ON r.FORWARD_OBJECT_ID = p.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON COALESCE(c.CLASS_ID, p.CLASS_ID) = cd.TYPE_ID
WHERE r.OBJECT_ID = 18208744;

EXIT;
