SET PAGESIZE 100
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

PROMPT === Check PartInstanceLibrary [18143953] location ===
SELECT 'COLLECTION_' AS TABLE_NAME, CAPTION_S_, CLASS_ID
FROM DESIGN12.COLLECTION_
WHERE OBJECT_ID = 18143953
UNION ALL
SELECT 'PART_' AS TABLE_NAME, NAME_S_, CLASS_ID
FROM DESIGN12.PART_
WHERE OBJECT_ID = 18143953;

PROMPT
PROMPT === Check children of PartInstanceLibrary in REL_COMMON ===
SELECT
    r.OBJECT_ID,
    r.SEQ_NUMBER,
    CASE
        WHEN c.OBJECT_ID IS NOT NULL THEN 'COLLECTION_'
        WHEN p.OBJECT_ID IS NOT NULL THEN 'PART_'
        ELSE 'NEITHER'
    END AS CHILD_TABLE,
    COALESCE(c.CAPTION_S_, p.NAME_S_, 'Unknown') AS NAME,
    cd.NICE_NAME AS TYPE,
    cd.TYPE_ID
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON COALESCE(c.CLASS_ID, p.CLASS_ID) = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18143953
ORDER BY r.SEQ_NUMBER;

PROMPT
PROMPT === Check specific nodes 18531240 and 18209343 ===
SELECT
    OBJECT_ID,
    CASE
        WHEN c.OBJECT_ID IS NOT NULL THEN 'COLLECTION_'
        WHEN p.OBJECT_ID IS NOT NULL THEN 'PART_'
        ELSE 'NOT_FOUND'
    END AS TABLE_LOCATION,
    COALESCE(c.CAPTION_S_, p.NAME_S_, 'N/A') AS NAME,
    cd.NICE_NAME AS TYPE
FROM (SELECT 18531240 AS OBJECT_ID FROM DUAL UNION ALL SELECT 18209343 FROM DUAL) ids
LEFT JOIN DESIGN12.COLLECTION_ c ON ids.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.PART_ p ON ids.OBJECT_ID = p.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON COALESCE(c.CLASS_ID, p.CLASS_ID) = cd.TYPE_ID;

PROMPT
PROMPT === Check if 18531240 and 18209343 have parents in REL_COMMON ===
SELECT
    r.OBJECT_ID,
    r.FORWARD_OBJECT_ID AS PARENT_ID,
    COALESCE(c.CAPTION_S_, p.NAME_S_, 'Unknown') AS PARENT_NAME
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.FORWARD_OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.PART_ p ON r.FORWARD_OBJECT_ID = p.OBJECT_ID
WHERE r.OBJECT_ID IN (18531240, 18209343);

EXIT;
