SET PAGESIZE 100
SET LINESIZE 400
SET FEEDBACK OFF
SET HEADING ON

PROMPT ============================================================
PROMPT Debug: EngineeringResourceLibrary Icon and Children
PROMPT ============================================================

PROMPT
PROMPT === What TYPE_ID does EngineeringResourceLibrary [18153685] have? ===
SELECT
    c.OBJECT_ID,
    c.CAPTION_S_,
    c.CLASS_ID,
    cd.NAME AS CLASS_NAME,
    cd.NICE_NAME,
    cd.TYPE_ID
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE c.OBJECT_ID = 18153685;

PROMPT
PROMPT === What are its children? ===
SELECT
    r.OBJECT_ID AS CHILD_ID,
    r.SEQ_NUMBER,
    COALESCE(c.CAPTION_S_, p.NAME_S_, 'NOT FOUND') AS CHILD_NAME,
    cd.NICE_NAME AS CLASS_TYPE,
    cd.TYPE_ID
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON COALESCE(c.CLASS_ID, p.CLASS_ID) = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18153685
ORDER BY r.SEQ_NUMBER;

PROMPT
PROMPT === What TYPE_ID does robcad_local [18154296] have for comparison? ===
SELECT
    c.OBJECT_ID,
    c.CAPTION_S_,
    c.CLASS_ID,
    cd.NAME AS CLASS_NAME,
    cd.NICE_NAME,
    cd.TYPE_ID
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE c.OBJECT_ID = 18154296;

EXIT;
