SET PAGESIZE 100
SET LINESIZE 300
SET FEEDBACK OFF
SET HEADING ON

PROMPT ============================================================
PROMPT ISSUE 1: EngineeringResourceLibrary [18153685] Icon Problem
PROMPT ============================================================

PROMPT
PROMPT === Check EngineeringResourceLibrary data ===
SELECT
    c.OBJECT_ID,
    c.CAPTION_S_,
    c.CLASS_ID,
    cd.NAME AS CLASS_NAME,
    cd.NICE_NAME,
    cd.TYPE_ID
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE c.OBJECT_ID = 18153685;

PROMPT
PROMPT === Check if TYPE_ID 164 has an icon ===
SELECT
    di.TYPE_ID,
    DBMS_LOB.GETLENGTH(di.CLASS_IMAGE) AS ICON_SIZE
FROM DESIGN12.DF_ICONS_DATA di
WHERE di.TYPE_ID = 164;

PROMPT
PROMPT === Compare all ResourceLibrary TYPE_IDs and their icons ===
SELECT
    cd.TYPE_ID,
    cd.NAME,
    cd.NICE_NAME,
    DBMS_LOB.GETLENGTH(di.CLASS_IMAGE) AS ICON_SIZE
FROM DESIGN12.CLASS_DEFINITIONS cd
LEFT JOIN DESIGN12.DF_ICONS_DATA di ON cd.TYPE_ID = di.TYPE_ID
WHERE cd.NICE_NAME LIKE '%ResourceLibrary%'
ORDER BY cd.TYPE_ID;

PROMPT
PROMPT === Check child of EngineeringResourceLibrary (robcad_local) ===
SELECT
    c.OBJECT_ID,
    c.CAPTION_S_,
    c.CLASS_ID,
    cd.NAME AS CLASS_NAME,
    cd.NICE_NAME,
    cd.TYPE_ID,
    DBMS_LOB.GETLENGTH(di.CLASS_IMAGE) AS ICON_SIZE
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
LEFT JOIN DESIGN12.DF_ICONS_DATA di ON cd.TYPE_ID = di.TYPE_ID
WHERE c.OBJECT_ID = 18154296;

PROMPT
PROMPT ============================================================
PROMPT ISSUE 2: COWL_SILL_SIDE [18208744] Missing 4 PartPrototypes
PROMPT ============================================================

PROMPT
PROMPT === Check COWL_SILL_SIDE node itself ===
SELECT
    c.OBJECT_ID,
    c.CAPTION_S_,
    c.CLASS_ID,
    cd.NAME AS CLASS_NAME,
    cd.NICE_NAME,
    cd.TYPE_ID
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE c.OBJECT_ID = 18208744;

PROMPT
PROMPT === Check children via REL_COMMON (COLLECTION_ table) ===
SELECT
    r.OBJECT_ID,
    c.CAPTION_S_,
    cd.NICE_NAME AS CLASS_TYPE,
    cd.TYPE_ID,
    r.SEQ_NUMBER
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18208744
ORDER BY r.SEQ_NUMBER;

PROMPT
PROMPT === Check children via REL_COMMON (PART_ table) ===
SELECT
    r.OBJECT_ID,
    p.NAME_S_,
    cd.NICE_NAME AS CLASS_TYPE,
    cd.TYPE_ID,
    r.SEQ_NUMBER
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON p.CLASS_ID = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18208744
ORDER BY r.SEQ_NUMBER;

PROMPT
PROMPT === Check ALL children (both COLLECTION_ and PART_) ===
SELECT
    r.OBJECT_ID,
    COALESCE(c.CAPTION_S_, p.NAME_S_, 'Unknown') AS NODE_NAME,
    cd.NICE_NAME AS CLASS_TYPE,
    cd.TYPE_ID,
    r.SEQ_NUMBER,
    CASE
        WHEN c.OBJECT_ID IS NOT NULL THEN 'COLLECTION_'
        WHEN p.OBJECT_ID IS NOT NULL THEN 'PART_'
        ELSE 'UNKNOWN'
    END AS TABLE_SOURCE
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON COALESCE(c.CLASS_ID, p.CLASS_ID) = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18208744
ORDER BY r.SEQ_NUMBER;

PROMPT
PROMPT ============================================================
PROMPT ISSUE 3: PartInstanceLibrary [18143953] Missing Children
PROMPT ============================================================

PROMPT
PROMPT === Check PartInstanceLibrary node itself ===
SELECT
    c.OBJECT_ID,
    c.CAPTION_S_,
    c.CLASS_ID,
    cd.NAME AS CLASS_NAME,
    cd.NICE_NAME,
    cd.TYPE_ID
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE c.OBJECT_ID = 18143953;

PROMPT
PROMPT === Also check in PART_ table ===
SELECT
    p.OBJECT_ID,
    p.NAME_S_,
    p.CLASS_ID,
    cd.NAME AS CLASS_NAME,
    cd.NICE_NAME,
    cd.TYPE_ID
FROM DESIGN12.PART_ p
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON p.CLASS_ID = cd.TYPE_ID
WHERE p.OBJECT_ID = 18143953;

PROMPT
PROMPT === Check children via REL_COMMON (COLLECTION_ table) ===
SELECT
    r.OBJECT_ID,
    c.CAPTION_S_,
    cd.NICE_NAME AS CLASS_TYPE,
    cd.TYPE_ID,
    r.SEQ_NUMBER
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18143953
ORDER BY r.SEQ_NUMBER;

PROMPT
PROMPT === Check children via REL_COMMON (PART_ table) ===
SELECT
    r.OBJECT_ID,
    p.NAME_S_,
    cd.NICE_NAME AS CLASS_TYPE,
    cd.TYPE_ID,
    r.SEQ_NUMBER
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON p.CLASS_ID = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18143953
ORDER BY r.SEQ_NUMBER;

PROMPT
PROMPT === Check ALL children (both COLLECTION_ and PART_) ===
SELECT
    r.OBJECT_ID,
    COALESCE(c.CAPTION_S_, p.NAME_S_, 'Unknown') AS NODE_NAME,
    cd.NICE_NAME AS CLASS_TYPE,
    cd.TYPE_ID,
    r.SEQ_NUMBER,
    CASE
        WHEN c.OBJECT_ID IS NOT NULL THEN 'COLLECTION_'
        WHEN p.OBJECT_ID IS NOT NULL THEN 'PART_'
        ELSE 'UNKNOWN'
    END AS TABLE_SOURCE
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON COALESCE(c.CLASS_ID, p.CLASS_ID) = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18143953
ORDER BY r.SEQ_NUMBER;

PROMPT
PROMPT === Count total children ===
SELECT COUNT(*) AS TOTAL_CHILDREN
FROM DESIGN12.REL_COMMON
WHERE FORWARD_OBJECT_ID = 18143953;

EXIT;
