SET PAGESIZE 200
SET LINESIZE 400
SET FEEDBACK OFF
SET HEADING ON

PROMPT ============================================================
PROMPT DEEP DEBUG: Understanding the actual database structure
PROMPT ============================================================

PROMPT
PROMPT === 1. Where is EngineeringResourceLibrary [18153685]? ===
SELECT
    'COLLECTION_' AS TABLE_NAME,
    c.OBJECT_ID,
    c.CAPTION_S_,
    c.CLASS_ID,
    cd.NAME AS CLASS_NAME,
    cd.NICE_NAME,
    cd.TYPE_ID
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE c.OBJECT_ID = 18153685
UNION ALL
SELECT
    'PART_' AS TABLE_NAME,
    p.OBJECT_ID,
    p.NAME_S_,
    p.CLASS_ID,
    cd.NAME AS CLASS_NAME,
    cd.NICE_NAME,
    cd.TYPE_ID
FROM DESIGN12.PART_ p
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON p.CLASS_ID = cd.TYPE_ID
WHERE p.OBJECT_ID = 18153685;

PROMPT
PROMPT === 2. What TYPE_ID should EngineeringResourceLibrary use? ===
PROMPT === (Compare with child robcad_local TYPE_ID 48) ===
SELECT
    c.OBJECT_ID,
    c.CAPTION_S_,
    cd.TYPE_ID,
    cd.NICE_NAME,
    DBMS_LOB.GETLENGTH(di.CLASS_IMAGE) AS ICON_SIZE_BYTES
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
LEFT JOIN DESIGN12.DF_ICONS_DATA di ON cd.TYPE_ID = di.TYPE_ID
WHERE c.OBJECT_ID IN (18153685, 18154296)
ORDER BY c.OBJECT_ID;

PROMPT
PROMPT === 3. Where is COWL_SILL_SIDE [18208744]? ===
SELECT
    'COLLECTION_' AS TABLE_NAME,
    c.OBJECT_ID,
    c.CAPTION_S_,
    c.CLASS_ID,
    cd.NAME AS CLASS_NAME,
    cd.NICE_NAME,
    cd.TYPE_ID
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE c.OBJECT_ID = 18208744
UNION ALL
SELECT
    'PART_' AS TABLE_NAME,
    p.OBJECT_ID,
    p.NAME_S_,
    p.CLASS_ID,
    cd.NAME AS CLASS_NAME,
    cd.NICE_NAME,
    cd.TYPE_ID
FROM DESIGN12.PART_ p
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON p.CLASS_ID = cd.TYPE_ID
WHERE p.OBJECT_ID = 18208744;

PROMPT
PROMPT === 4. What are COWL_SILL_SIDE's children in REL_COMMON? ===
SELECT
    r.OBJECT_ID AS CHILD_ID,
    r.SEQ_NUMBER,
    CASE
        WHEN c.OBJECT_ID IS NOT NULL THEN 'COLLECTION_'
        WHEN p.OBJECT_ID IS NOT NULL THEN 'PART_'
        ELSE 'NOT FOUND'
    END AS CHILD_IN_TABLE,
    COALESCE(c.CAPTION_S_, p.NAME_S_, '*** NOT IN ANY TABLE ***') AS CHILD_NAME,
    COALESCE(c.CLASS_ID, p.CLASS_ID) AS CLASS_ID,
    cd.NICE_NAME AS CLASS_TYPE,
    cd.TYPE_ID
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON COALESCE(c.CLASS_ID, p.CLASS_ID) = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18208744
ORDER BY r.SEQ_NUMBER;

PROMPT
PROMPT === 5. Where is PartInstanceLibrary [18143953]? ===
SELECT
    'COLLECTION_' AS TABLE_NAME,
    c.OBJECT_ID,
    c.CAPTION_S_,
    c.CLASS_ID,
    cd.NAME AS CLASS_NAME,
    cd.NICE_NAME,
    cd.TYPE_ID
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE c.OBJECT_ID = 18143953
UNION ALL
SELECT
    'PART_' AS TABLE_NAME,
    p.OBJECT_ID,
    p.NAME_S_,
    p.CLASS_ID,
    cd.NAME AS CLASS_NAME,
    cd.NICE_NAME,
    cd.TYPE_ID
FROM DESIGN12.PART_ p
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON p.CLASS_ID = cd.TYPE_ID
WHERE p.OBJECT_ID = 18143953;

PROMPT
PROMPT === 6. What are PartInstanceLibrary's children in REL_COMMON? ===
SELECT
    r.OBJECT_ID AS CHILD_ID,
    r.SEQ_NUMBER,
    CASE
        WHEN c.OBJECT_ID IS NOT NULL THEN 'COLLECTION_'
        WHEN p.OBJECT_ID IS NOT NULL THEN 'PART_'
        ELSE 'NOT FOUND'
    END AS CHILD_IN_TABLE,
    COALESCE(c.CAPTION_S_, p.NAME_S_, '*** NOT IN ANY TABLE ***') AS CHILD_NAME,
    COALESCE(c.CLASS_ID, p.CLASS_ID) AS CLASS_ID,
    cd.NICE_NAME AS CLASS_TYPE,
    cd.TYPE_ID
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON COALESCE(c.CLASS_ID, p.CLASS_ID) = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18143953
ORDER BY r.SEQ_NUMBER;

PROMPT
PROMPT === 7. TEST: Will our new query extract COWL_SILL_SIDE children? ===
SELECT
    '999|' ||
    r.FORWARD_OBJECT_ID || '|' ||
    p.OBJECT_ID || '|' ||
    NVL(p.NAME_S_, 'Unnamed') || '|' ||
    NVL(p.NAME_S_, 'Unnamed') || '|' ||
    NVL(p.EXTERNALID_S_, '') || '|' ||
    TO_CHAR(r.SEQ_NUMBER) || '|' ||
    NVL(cd.NAME, 'class PmPart') || '|' ||
    NVL(cd.NICE_NAME, 'Part') || '|' ||
    TO_CHAR(cd.TYPE_ID) AS EXTRACTED_LINE
FROM DESIGN12.REL_COMMON r
INNER JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON p.CLASS_ID = cd.TYPE_ID
WHERE NOT EXISTS (SELECT 1 FROM DESIGN12.COLLECTION_ c WHERE c.OBJECT_ID = p.OBJECT_ID)
  AND r.FORWARD_OBJECT_ID IN (18208744, 18143953);

PROMPT
PROMPT === 8. Check if these nodes are actually in the project tree ===
SELECT
    LEVEL AS TREE_LEVEL,
    c.OBJECT_ID,
    c.CAPTION_S_,
    cd.NICE_NAME
FROM DESIGN12.REL_COMMON r
INNER JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
START WITH r.FORWARD_OBJECT_ID = 18140190
CONNECT BY NOCYCLE PRIOR r.OBJECT_ID = r.FORWARD_OBJECT_ID
WHERE c.OBJECT_ID IN (18208744, 18143953, 18153685);

EXIT;
