-- Find COWL_SILL_SIDE children by their actual names
SET LINESIZE 200
SET PAGESIZE 50000

PROMPT Searching for COWL_SILL_SIDE PartPrototype children by name:

SELECT
    p.OBJECT_ID,
    p.NAME_S_,
    p.CLASS_ID,
    cd.NICE_NAME,
    cd.TYPE_ID
FROM DESIGN12.PART_ p
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON p.CLASS_ID = cd.TYPE_ID
WHERE p.NAME_S_ LIKE '%JL34-1610110%'
   OR p.NAME_S_ LIKE '%FNA11786300%'
   OR p.NAME_S_ LIKE '%FNA11786290%'
   OR p.NAME_S_ LIKE '%NL34-1610111%'
ORDER BY p.NAME_S_;

PROMPT
PROMPT Checking their parent relationships:

SELECT
    p.OBJECT_ID,
    p.NAME_S_,
    r.FORWARD_OBJECT_ID as PARENT_ID
FROM DESIGN12.PART_ p
INNER JOIN DESIGN12.REL_COMMON r ON p.OBJECT_ID = r.OBJECT_ID
WHERE p.NAME_S_ LIKE '%JL34-1610110%'
   OR p.NAME_S_ LIKE '%FNA11786300%'
   OR p.NAME_S_ LIKE '%FNA11786290%'
   OR p.NAME_S_ LIKE '%NL34-1610111%'
ORDER BY p.NAME_S_, r.FORWARD_OBJECT_ID;

EXIT
