SET PAGESIZE 100
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

PROMPT === Step 1: Find all children of COWL_SILL_SIDE [18208744] in REL_COMMON ===
SELECT
    r.OBJECT_ID,
    r.SEQ_NUMBER,
    r.FORWARD_OBJECT_ID AS PARENT_ID
FROM DESIGN12.REL_COMMON r
WHERE r.FORWARD_OBJECT_ID = 18208744
ORDER BY r.SEQ_NUMBER;

PROMPT
PROMPT === Step 2: Check which are ghost nodes (in REL_COMMON but not in physical tables) ===
SELECT
    r.OBJECT_ID,
    CASE
        WHEN c.OBJECT_ID IS NOT NULL THEN 'EXISTS_IN_COLLECTION'
        WHEN p.OBJECT_ID IS NOT NULL THEN 'EXISTS_IN_PART'
        WHEN rs.OBJECT_ID IS NOT NULL THEN 'EXISTS_IN_ROBCADSTUDY'
        WHEN rn.OBJECT_ID IS NOT NULL THEN 'EXISTS_IN_ROBCADNODE'
        ELSE 'GHOST_NODE'
    END AS NODE_STATUS
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
LEFT JOIN ROBUST_ROBCAD_ORACLE.ROBCADSTUDY_ rs ON r.OBJECT_ID = rs.OBJECT_ID
LEFT JOIN ROBUST_ROBCAD_ORACLE.ROBCADNODE_ rn ON r.OBJECT_ID = rn.OBJECT_ID
WHERE r.FORWARD_OBJECT_ID = 18208744
ORDER BY r.SEQ_NUMBER;

PROMPT
PROMPT === Step 3: For ghost nodes, find their children (the actual PartPrototypes) ===
SELECT
    r1.OBJECT_ID AS GHOST_NODE_ID,
    r2.OBJECT_ID AS ACTUAL_CHILD_ID,
    CASE
        WHEN c.OBJECT_ID IS NOT NULL THEN 'COLLECTION_'
        WHEN p.OBJECT_ID IS NOT NULL THEN 'PART_'
        ELSE 'UNKNOWN'
    END AS CHILD_TABLE,
    COALESCE(c.CAPTION_S_, p.NAME_S_, 'Unknown') AS CHILD_NAME,
    cd.NICE_NAME AS CHILD_TYPE
FROM DESIGN12.REL_COMMON r1
INNER JOIN DESIGN12.REL_COMMON r2 ON r1.OBJECT_ID = r2.FORWARD_OBJECT_ID
LEFT JOIN DESIGN12.COLLECTION_ c_ghost ON r1.OBJECT_ID = c_ghost.OBJECT_ID
LEFT JOIN DESIGN12.PART_ p_ghost ON r1.OBJECT_ID = p_ghost.OBJECT_ID
LEFT JOIN DESIGN12.COLLECTION_ c ON r2.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.PART_ p ON r2.OBJECT_ID = p.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON COALESCE(c.CLASS_ID, p.CLASS_ID) = cd.TYPE_ID
WHERE r1.FORWARD_OBJECT_ID = 18208744
  AND c_ghost.OBJECT_ID IS NULL  -- Ghost node not in COLLECTION_
  AND p_ghost.OBJECT_ID IS NULL  -- Ghost node not in PART_
ORDER BY r1.OBJECT_ID, r2.SEQ_NUMBER;

EXIT;
