SET PAGESIZE 100
SET LINESIZE 400
SET FEEDBACK OFF
SET HEADING ON

PROMPT === Simple connection test ===
SELECT COUNT(*) AS TOTAL_PARTS FROM DESIGN12.PART_ WHERE ROWNUM <= 10;

PROMPT === COWL_SILL_SIDE children IDs ===
SELECT r.OBJECT_ID, r.SEQ_NUMBER
FROM DESIGN12.REL_COMMON r
WHERE r.FORWARD_OBJECT_ID = 18208744
ORDER BY r.SEQ_NUMBER;

PROMPT === Check one ID in PART_ table ===
SELECT OBJECT_ID, NAME_S_, CLASS_ID FROM DESIGN12.PART_ WHERE OBJECT_ID = 18208702;

EXIT;
