SET PAGESIZE 100
SET LINESIZE 300
SET FEEDBACK OFF
SET HEADING ON

PROMPT === Test Dynamic Icon Lookup for TYPE_ID 164 ===

-- Test the COALESCE logic for TYPE_ID 164
SELECT
    cd.TYPE_ID AS CHILD_TYPE_ID,
    cd.NICE_NAME AS CHILD_NAME,
    cd.DERIVED_FROM AS PARENT_TYPE_ID,
    (SELECT di.TYPE_ID FROM DESIGN12.DF_ICONS_DATA di WHERE di.TYPE_ID = cd.TYPE_ID) AS HAS_OWN_ICON,
    (SELECT di.TYPE_ID FROM DESIGN12.DF_ICONS_DATA di WHERE di.TYPE_ID = cd.DERIVED_FROM) AS PARENT_HAS_ICON,
    COALESCE(
        (SELECT di.TYPE_ID FROM DESIGN12.DF_ICONS_DATA di WHERE di.TYPE_ID = cd.TYPE_ID),
        (SELECT di.TYPE_ID FROM DESIGN12.DF_ICONS_DATA di WHERE di.TYPE_ID = cd.DERIVED_FROM),
        cd.TYPE_ID
    ) AS RESOLVED_TYPE_ID
FROM DESIGN12.CLASS_DEFINITIONS cd
WHERE cd.TYPE_ID = 164;

PROMPT
PROMPT === Expected: RESOLVED_TYPE_ID should be 48 (parent) ===

EXIT;
