-- Test schema access
SET LINESIZE 200
SET PAGESIZE 50000
SET FEEDBACK ON

PROMPT Testing schema access...
PROMPT
PROMPT 1. Try querying COLLECTION_ directly:

SELECT COUNT(*) as COLLECTION_COUNT
FROM ROBUST_ROBCAD_ORACLE.COLLECTION_;

PROMPT
PROMPT 2. Try querying specific node 18153685:

SELECT OBJECT_ID, NAME, CLASS_ID
FROM ROBUST_ROBCAD_ORACLE.COLLECTION_
WHERE OBJECT_ID = 18153685;

PROMPT
PROMPT 3. Check if DF_ICONS_DATA is accessible:

SELECT COUNT(*) as ICON_COUNT
FROM ROBUST_ROBCAD_ORACLE.DF_ICONS_DATA;

PROMPT
PROMPT 4. List available tables in ROBUST_ROBCAD_ORACLE schema:

SELECT table_name
FROM all_tables
WHERE owner = 'ROBUST_ROBCAD_ORACLE'
AND table_name LIKE '%CLASS%'
ORDER BY table_name;

EXIT
