SET PAGESIZE 100
SET LINESIZE 400
SET FEEDBACK OFF
SET HEADING ON

PROMPT ============================================================
PROMPT Let's understand the ACTUAL structure in the database
PROMPT ============================================================

PROMPT
PROMPT === 1. Is COWL_SILL_SIDE in COLLECTION_ or PART_? ===
SELECT 'COLLECTION_' AS LOCATION, COUNT(*) AS COUNT FROM DESIGN12.COLLECTION_ WHERE OBJECT_ID = 18208744
UNION ALL
SELECT 'PART_' AS LOCATION, COUNT(*) AS COUNT FROM DESIGN12.PART_ WHERE OBJECT_ID = 18208744;

PROMPT
PROMPT === 2. Is PartInstanceLibrary in COLLECTION_ or PART_? ===
SELECT 'COLLECTION_' AS LOCATION, COUNT(*) AS COUNT FROM DESIGN12.COLLECTION_ WHERE OBJECT_ID = 18143953
UNION ALL
SELECT 'PART_' AS LOCATION, COUNT(*) AS COUNT FROM DESIGN12.PART_ WHERE OBJECT_ID = 18143953;

PROMPT
PROMPT === 3. Show COWL_SILL_SIDE children from REL_COMMON ===
SELECT
    r.OBJECT_ID,
    CASE
        WHEN EXISTS (SELECT 1 FROM DESIGN12.COLLECTION_ WHERE OBJECT_ID = r.OBJECT_ID) THEN 'COLLECTION_'
        WHEN EXISTS (SELECT 1 FROM DESIGN12.PART_ WHERE OBJECT_ID = r.OBJECT_ID) THEN 'PART_'
        ELSE 'NEITHER'
    END AS CHILD_TABLE,
    r.SEQ_NUMBER
FROM DESIGN12.REL_COMMON r
WHERE r.FORWARD_OBJECT_ID = 18208744
ORDER BY r.SEQ_NUMBER;

PROMPT
PROMPT === 4. Show PartInstanceLibrary children from REL_COMMON ===
SELECT
    r.OBJECT_ID,
    CASE
        WHEN EXISTS (SELECT 1 FROM DESIGN12.COLLECTION_ WHERE OBJECT_ID = r.OBJECT_ID) THEN 'COLLECTION_'
        WHEN EXISTS (SELECT 1 FROM DESIGN12.PART_ WHERE OBJECT_ID = r.OBJECT_ID) THEN 'PART_'
        ELSE 'NEITHER'
    END AS CHILD_TABLE,
    r.SEQ_NUMBER
FROM DESIGN12.REL_COMMON r
WHERE r.FORWARD_OBJECT_ID = 18143953
ORDER BY r.SEQ_NUMBER;

PROMPT
PROMPT === 5. Would the CURRENT SQL query extract COWL_SILL_SIDE children? ===
PROMPT === Testing the existing PART_ extraction WHERE clause ===
SELECT
    'Would extract: ' || r.OBJECT_ID AS DEBUG_MESSAGE
FROM DESIGN12.REL_COMMON r
INNER JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
WHERE r.FORWARD_OBJECT_ID = 18208744
  AND NOT EXISTS (SELECT 1 FROM DESIGN12.COLLECTION_ c WHERE c.OBJECT_ID = p.OBJECT_ID)
  AND EXISTS (
    SELECT 1 FROM DESIGN12.REL_COMMON r2
    INNER JOIN DESIGN12.COLLECTION_ c2 ON r2.OBJECT_ID = c2.OBJECT_ID
    WHERE c2.OBJECT_ID = r.FORWARD_OBJECT_ID
      AND c2.OBJECT_ID IN (
        SELECT c3.OBJECT_ID
        FROM DESIGN12.REL_COMMON r3
        INNER JOIN DESIGN12.COLLECTION_ c3 ON r3.OBJECT_ID = c3.OBJECT_ID
        START WITH r3.FORWARD_OBJECT_ID = 18140190
        CONNECT BY NOCYCLE PRIOR r3.OBJECT_ID = r3.FORWARD_OBJECT_ID
      )
  );

PROMPT
PROMPT === 6. Would the CURRENT SQL query extract PartInstanceLibrary children? ===
SELECT
    'Would extract: ' || r.OBJECT_ID AS DEBUG_MESSAGE
FROM DESIGN12.REL_COMMON r
INNER JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
WHERE r.FORWARD_OBJECT_ID = 18143953
  AND NOT EXISTS (SELECT 1 FROM DESIGN12.COLLECTION_ c WHERE c.OBJECT_ID = p.OBJECT_ID)
  AND EXISTS (
    SELECT 1 FROM DESIGN12.REL_COMMON r2
    INNER JOIN DESIGN12.COLLECTION_ c2 ON r2.OBJECT_ID = c2.OBJECT_ID
    WHERE c2.OBJECT_ID = r.FORWARD_OBJECT_ID
      AND c2.OBJECT_ID IN (
        SELECT c3.OBJECT_ID
        FROM DESIGN12.REL_COMMON r3
        INNER JOIN DESIGN12.COLLECTION_ c3 ON r3.OBJECT_ID = c3.OBJECT_ID
        START WITH r3.FORWARD_OBJECT_ID = 18140190
        CONNECT BY NOCYCLE PRIOR r3.OBJECT_ID = r3.FORWARD_OBJECT_ID
      )
  );

PROMPT
PROMPT === 7. WHY NOT? Let's check each condition separately for COWL_SILL_SIDE ===
PROMPT
PROMPT --- Is 18208744 in the project tree as a COLLECTION_? ---
SELECT c3.OBJECT_ID, c3.CAPTION_S_
FROM DESIGN12.REL_COMMON r3
INNER JOIN DESIGN12.COLLECTION_ c3 ON r3.OBJECT_ID = c3.OBJECT_ID
START WITH r3.FORWARD_OBJECT_ID = 18140190
CONNECT BY NOCYCLE PRIOR r3.OBJECT_ID = r3.FORWARD_OBJECT_ID
WHERE c3.OBJECT_ID = 18208744;

EXIT;
