-- Verify PartInstanceLibrary parent relationship
SET LINESIZE 200
SET PAGESIZE 50000

PROMPT Checking PartInstanceLibrary (18143953) parent:

SELECT
    r.OBJECT_ID,
    r.FORWARD_OBJECT_ID as PARENT_ID,
    c.CAPTION_S_ as PARENT_CAPTION,
    parent_cd.NICE_NAME as PARENT_TYPE
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.FORWARD_OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS parent_cd ON c.CLASS_ID = parent_cd.TYPE_ID
WHERE r.OBJECT_ID = 18143953;

PROMPT
PROMPT Checking children P702 and P736 parents:

SELECT
    r.OBJECT_ID as CHILD_ID,
    p.NAME_S_ as CHILD_NAME,
    r.FORWARD_OBJECT_ID as PARENT_ID
FROM DESIGN12.REL_COMMON r
INNER JOIN DESIGN12.PART_ p ON r.OBJECT_ID = p.OBJECT_ID
WHERE r.OBJECT_ID IN (18209343, 18531240)
ORDER BY r.OBJECT_ID;

EXIT
