SET PAGESIZE 1000
SET LINESIZE 200
SET FEEDBACK OFF
SET HEADING ON

PROMPT ========================================
PROMPT Check if any ToolPrototypes are in FORD_DEARBORN project
PROMPT ========================================

-- Count ToolPrototypes in project (via REL_COMMON - CORRECTED)
WITH project_tree AS (
    SELECT c.OBJECT_ID
    FROM DESIGN12.COLLECTION_ c
    START WITH c.OBJECT_ID = 18140190
    CONNECT BY NOCYCLE PRIOR c.OBJECT_ID = (
        SELECT rc.FORWARD_OBJECT_ID
        FROM DESIGN12.REL_COMMON rc
        WHERE rc.OBJECT_ID = PRIOR c.OBJECT_ID
        AND ROWNUM = 1
    )
)
SELECT
    'Via REL_COMMON' as METHOD,
    COUNT(*) as COUNT
FROM DESIGN12.TOOLPROTOTYPE_ tp
INNER JOIN DESIGN12.REL_COMMON rc ON tp.OBJECT_ID = rc.OBJECT_ID
WHERE rc.FORWARD_OBJECT_ID IN (SELECT OBJECT_ID FROM project_tree);

PROMPT
PROMPT ========================================
PROMPT Sample ToolPrototypes in FORD_DEARBORN (if any)
PROMPT ========================================

WITH project_tree AS (
    SELECT c.OBJECT_ID
    FROM DESIGN12.COLLECTION_ c
    START WITH c.OBJECT_ID = 18140190
    CONNECT BY NOCYCLE PRIOR c.OBJECT_ID = (
        SELECT rc2.FORWARD_OBJECT_ID
        FROM DESIGN12.REL_COMMON rc2
        WHERE rc2.OBJECT_ID = PRIOR c.OBJECT_ID
        AND ROWNUM = 1
    )
)
SELECT
    tp.OBJECT_ID,
    tp.NAME_S_,
    tp.CAPTION_S_,
    rc.FORWARD_OBJECT_ID as PARENT_ID,
    c.CAPTION_S_ as PARENT_COLLECTION,
    cd.NAME as CLASS_NAME,
    cd.TYPE_ID
FROM DESIGN12.TOOLPROTOTYPE_ tp
INNER JOIN DESIGN12.REL_COMMON rc ON tp.OBJECT_ID = rc.OBJECT_ID
LEFT JOIN DESIGN12.COLLECTION_ c ON rc.FORWARD_OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON tp.CLASS_ID = cd.TYPE_ID
WHERE rc.FORWARD_OBJECT_ID IN (SELECT OBJECT_ID FROM project_tree)
AND ROWNUM <= 10;

EXIT;
