SET PAGESIZE 1000
SET LINESIZE 200
SET FEEDBACK OFF
SET HEADING ON

PROMPT ========================================
PROMPT ToolPrototype Parent Relationship Check
PROMPT ========================================

-- Check how ToolPrototypes relate to collections
SELECT
    tp.OBJECT_ID as TOOL_OBJECT_ID,
    tp.NAME_S_ as TOOL_NAME,
    tp.COLLECTIONS_VR_,
    c.CAPTION_S_ as PARENT_VIA_COLLECTIONS_VR,
    c.OBJECT_ID as PARENT_COLLECTION_ID,
    rc.FORWARD_OBJECT_ID as PARENT_VIA_REL_COMMON,
    rc.OBJECT_ID as REL_COMMON_OBJECT_ID
FROM DESIGN12.TOOLPROTOTYPE_ tp
LEFT JOIN DESIGN12.COLLECTION_ c ON tp.COLLECTIONS_VR_ = c.OBJECT_ID
LEFT JOIN DESIGN12.REL_COMMON rc ON tp.OBJECT_ID = rc.OBJECT_ID
WHERE ROWNUM <= 10
ORDER BY tp.OBJECT_ID;

PROMPT
PROMPT ========================================
PROMPT Check if COLLECTIONS_VR_ points to valid collections
PROMPT ========================================

SELECT
    COUNT(*) as TOTAL_TOOLPROTOTYPES,
    COUNT(tp.COLLECTIONS_VR_) as WITH_COLLECTIONS_VR,
    COUNT(CASE WHEN c.OBJECT_ID IS NOT NULL THEN 1 END) as VALID_COLLECTION_LINK
FROM DESIGN12.TOOLPROTOTYPE_ tp
LEFT JOIN DESIGN12.COLLECTION_ c ON tp.COLLECTIONS_VR_ = c.OBJECT_ID;

PROMPT
PROMPT ========================================
PROMPT Check REL_COMMON relationships for ToolPrototypes
PROMPT ========================================

SELECT
    COUNT(*) as TOTAL_TOOLPROTOTYPES,
    COUNT(rc.OBJECT_ID) as WITH_REL_COMMON_ENTRY,
    COUNT(rc.FORWARD_OBJECT_ID) as WITH_FORWARD_OBJECT_ID
FROM DESIGN12.TOOLPROTOTYPE_ tp
LEFT JOIN DESIGN12.REL_COMMON rc ON tp.OBJECT_ID = rc.OBJECT_ID;

PROMPT
PROMPT ========================================
PROMPT Sample: How existing COLLECTION_ uses REL_COMMON
PROMPT ========================================

SELECT
    c.OBJECT_ID,
    c.CAPTION_S_,
    rc.FORWARD_OBJECT_ID as PARENT_ID,
    pc.CAPTION_S_ as PARENT_NAME
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.REL_COMMON rc ON c.OBJECT_ID = rc.OBJECT_ID
LEFT JOIN DESIGN12.COLLECTION_ pc ON rc.FORWARD_OBJECT_ID = pc.OBJECT_ID
WHERE c.OBJECT_ID IN (18140190, 18153685, 18153686, 18153687, 18153688)
ORDER BY c.OBJECT_ID;

PROMPT
PROMPT ========================================
PROMPT Check if any ToolPrototypes are in FORD_DEARBORN project
PROMPT ========================================

-- Count ToolPrototypes in project (via COLLECTIONS_VR_)
SELECT
    'Via COLLECTIONS_VR_' as METHOD,
    COUNT(*) as COUNT
FROM DESIGN12.TOOLPROTOTYPE_ tp
WHERE EXISTS (
    SELECT 1 FROM DESIGN12.COLLECTION_ c
    WHERE c.OBJECT_ID = tp.COLLECTIONS_VR_
    START WITH c.OBJECT_ID = 18140190
    CONNECT BY NOCYCLE PRIOR c.OBJECT_ID = NVL((
        SELECT rc.FORWARD_OBJECT_ID
        FROM DESIGN12.REL_COMMON rc
        WHERE rc.OBJECT_ID = PRIOR c.OBJECT_ID
        AND ROWNUM = 1
    ), -1)
);

PROMPT
PROMPT ========================================
PROMPT Sample ToolPrototypes in FORD_DEARBORN (if any)
PROMPT ========================================

SELECT
    tp.OBJECT_ID,
    tp.NAME_S_,
    tp.CAPTION_S_,
    tp.COLLECTIONS_VR_,
    c.CAPTION_S_ as PARENT_COLLECTION
FROM DESIGN12.TOOLPROTOTYPE_ tp
LEFT JOIN DESIGN12.COLLECTION_ c ON tp.COLLECTIONS_VR_ = c.OBJECT_ID
WHERE EXISTS (
    SELECT 1 FROM DESIGN12.COLLECTION_ c2
    WHERE c2.OBJECT_ID = tp.COLLECTIONS_VR_
    START WITH c2.OBJECT_ID = 18140190
    CONNECT BY NOCYCLE PRIOR c2.OBJECT_ID = NVL((
        SELECT rc.FORWARD_OBJECT_ID
        FROM DESIGN12.REL_COMMON rc
        WHERE rc.OBJECT_ID = PRIOR c2.OBJECT_ID
        AND ROWNUM = 1
    ), -1)
)
AND ROWNUM <= 5;

EXIT;
