SET PAGESIZE 1000
SET LINESIZE 200
SET FEEDBACK OFF
SET HEADING ON

PROMPT ========================================
PROMPT Operation Parent Relationship Check
PROMPT ========================================

-- Check how Operations relate to collections/parents
SELECT
    op.OBJECT_ID as OP_OBJECT_ID,
    op.NAME_S_ as OP_NAME,
    op.CAPTION_S_ as OP_CAPTION,
    rc.FORWARD_OBJECT_ID as PARENT_VIA_REL_COMMON,
    c.CAPTION_S_ as PARENT_COLLECTION_NAME,
    cd.NAME as OP_CLASS_NAME,
    cd.TYPE_ID as OP_TYPE_ID
FROM DESIGN12.OPERATION_ op
LEFT JOIN DESIGN12.REL_COMMON rc ON op.OBJECT_ID = rc.OBJECT_ID
LEFT JOIN DESIGN12.COLLECTION_ c ON rc.FORWARD_OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON op.CLASS_ID = cd.TYPE_ID
WHERE op.NAME_S_ IN ('MOV_HOME', 'COMM_PICK01', 'COMM_PICK02', 'PROGRAM_DATA', 'SITE_BACKUP')
   OR op.CAPTION_S_ IN ('MOV_HOME', 'COMM_PICK01', 'COMM_PICK02', 'PROGRAM_DATA', 'SITE_BACKUP')
ORDER BY op.NAME_S_;

PROMPT
PROMPT ========================================
PROMPT Check total Operations and parent relationships
PROMPT ========================================

SELECT
    COUNT(*) as TOTAL_OPERATIONS,
    COUNT(rc.OBJECT_ID) as WITH_REL_COMMON_ENTRY,
    COUNT(rc.FORWARD_OBJECT_ID) as WITH_FORWARD_OBJECT_ID,
    COUNT(CASE WHEN c.OBJECT_ID IS NOT NULL THEN 1 END) as PARENT_IS_COLLECTION
FROM DESIGN12.OPERATION_ op
LEFT JOIN DESIGN12.REL_COMMON rc ON op.OBJECT_ID = rc.OBJECT_ID
LEFT JOIN DESIGN12.COLLECTION_ c ON rc.FORWARD_OBJECT_ID = c.OBJECT_ID;

PROMPT
PROMPT ========================================
PROMPT Sample Operations with parent info
PROMPT ========================================

SELECT
    op.OBJECT_ID,
    op.NAME_S_,
    op.CAPTION_S_,
    rc.FORWARD_OBJECT_ID as PARENT_ID,
    cd.NAME as CLASS_NAME,
    cd.TYPE_ID
FROM DESIGN12.OPERATION_ op
LEFT JOIN DESIGN12.REL_COMMON rc ON op.OBJECT_ID = rc.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON op.CLASS_ID = cd.TYPE_ID
WHERE ROWNUM <= 10
ORDER BY op.OBJECT_ID;

EXIT;
