SET PAGESIZE 100
SET LINESIZE 300
SET FEEDBACK OFF

-- Analyze EXTERNALID_S_ which contains timestamps
-- Format: PP-DESIGN12-DD-M-YYYY-H-MM-SS-ProjectID-ObjectID
SELECT
    c.OBJECT_ID,
    c.CAPTION_S_,
    c.EXTERNALID_S_,
    -- Extract timestamp from EXTERNALID_S_
    SUBSTR(c.EXTERNALID_S_, 13) AS TIMESTAMP_PART,
    r.OBJECT_VERSION_ID,
    TO_CHAR(c.MODIFICATIONDATE_DA_, 'DD/MM/YYYY HH24:MI:SS') AS MOD_DATE
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
WHERE r.FORWARD_OBJECT_ID = 18140190
ORDER BY c.EXTERNALID_S_;

EXIT;
