SET PAGESIZE 100
SET LINESIZE 200
SET FEEDBACK OFF

-- Check if OBJECT_VERSION_ID correlates with custom order
SELECT
    r.OBJECT_VERSION_ID,
    r.SEQ_NUMBER,
    c.OBJECT_ID,
    c.CAPTION_S_,
    TO_CHAR(c.MODIFICATIONDATE_DA_, 'DD/MM/YYYY HH24:MI:SS') AS MOD_DATE
FROM DESIGN12.REL_COMMON r
INNER JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
WHERE r.FORWARD_OBJECT_ID = 18140190
ORDER BY r.OBJECT_VERSION_ID;

EXIT;
