SET PAGESIZE 1000
SET LINESIZE 200
SET FEEDBACK OFF

-- Check ALL columns in COLLECTION_ table that might be dates
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH
FROM DBA_TAB_COLUMNS
WHERE TABLE_NAME = 'COLLECTION_'
  AND OWNER = 'DESIGN12'
  AND (DATA_TYPE = 'DATE' OR DATA_TYPE LIKE 'TIMESTAMP%')
ORDER BY COLUMN_ID;

-- Also check if there's a CREATIONDATE or similar
SELECT COLUMN_NAME, DATA_TYPE
FROM DBA_TAB_COLUMNS
WHERE TABLE_NAME = 'COLLECTION_'
  AND OWNER = 'DESIGN12'
  AND (COLUMN_NAME LIKE '%CREAT%' OR COLUMN_NAME LIKE '%INSERT%' OR COLUMN_NAME LIKE '%DATE%')
ORDER BY COLUMN_NAME;

EXIT;
