SET PAGESIZE 100
SET LINESIZE 300
SET FEEDBACK OFF

-- Check if ROWID (physical storage order) matches Siemens order
SELECT
    r.ROWID AS ROW_ID,
    r.OBJECT_VERSION_ID,
    c.OBJECT_ID,
    c.CAPTION_S_
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
WHERE r.FORWARD_OBJECT_ID = 18140190
ORDER BY r.ROWID;

EXIT;
