SET PAGESIZE 100
SET LINESIZE 200
SET FEEDBACK OFF

-- Get Level 1 children with their actual modification dates
SELECT
    c.OBJECT_ID,
    c.CAPTION_S_,
    TO_CHAR(c.MODIFICATIONDATE_DA_, 'DD/MM/YYYY HH24:MI:SS') AS MOD_DATE,
    c.EXTERNALID_S_
FROM DESIGN12.REL_COMMON r
INNER JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
WHERE r.FORWARD_OBJECT_ID = 18140190
ORDER BY c.MODIFICATIONDATE_DA_, c.OBJECT_ID;

EXIT;
