SET PAGESIZE 100
SET LINESIZE 400
SET FEEDBACK OFF

-- Get ALL columns from REL_COMMON for our relationships
SELECT *
FROM DESIGN12.REL_COMMON
WHERE FORWARD_OBJECT_ID = 18140190
ORDER BY OBJECT_ID;

EXIT;
