SET PAGESIZE 100
SET LINESIZE 200
SET FEEDBACK OFF

-- Check if PartInstanceLibrary exists and how it's related
SELECT
    c.OBJECT_ID,
    c.CAPTION_S_,
    c.EXTERNALID_S_,
    r.FORWARD_OBJECT_ID AS PARENT_ID,
    r.SEQ_NUMBER,
    r.OBJECT_VERSION_ID,
    cd.NICE_NAME AS CLASS_TYPE
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.REL_COMMON r ON c.OBJECT_ID = r.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE c.CAPTION_S_ LIKE '%PartInstance%'
  AND r.FORWARD_OBJECT_ID = 18140190;

EXIT;
