SET PAGESIZE 20
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Check all columns in CLASS_DEFINITIONS for icon-related fields
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH
FROM DBA_TAB_COLUMNS
WHERE OWNER = 'DESIGN12'
  AND TABLE_NAME = 'CLASS_DEFINITIONS'
ORDER BY COLUMN_NAME;
EXIT;