SET PAGESIZE 50
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Check CLASS_DEFINITIONS table structure and sample data
SELECT COLUMN_NAME, DATA_TYPE 
FROM DBA_TAB_COLUMNS 
WHERE OWNER = 'DESIGN1' 
  AND TABLE_NAME = 'CLASS_DEFINITIONS'
ORDER BY COLUMN_ID;
EXIT;