SET PAGESIZE 50
SET FEEDBACK OFF
SELECT 'DESIGN3 DFPROJECT count: ' || COUNT(*) FROM DESIGN3.DFPROJECT;
SELECT 'DESIGN4 DFPROJECT count: ' || COUNT(*) FROM DESIGN4.DFPROJECT;
SELECT 'DESIGN5 DFPROJECT count: ' || COUNT(*) FROM DESIGN5.DFPROJECT;
EXIT;
