SET PAGESIZE 100
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Look for customization or user-defined tables
SELECT TABLE_NAME
FROM DBA_TABLES
WHERE OWNER = 'DESIGN12'
  AND (UPPER(TABLE_NAME) LIKE '%CUSTOM%'
       OR UPPER(TABLE_NAME) LIKE '%USER%'
       OR UPPER(TABLE_NAME) LIKE '%DEFINITION%'
       OR UPPER(TABLE_NAME) LIKE '%METADATA%'
       OR UPPER(TABLE_NAME) LIKE '%PROPERTY%')
ORDER BY TABLE_NAME;
EXIT;