SET PAGESIZE 30
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Check FILE_ table structure
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH
FROM DBA_TAB_COLUMNS
WHERE OWNER = 'DESIGN12'
  AND TABLE_NAME = 'FILE_'
ORDER BY COLUMN_NAME;
EXIT;