SET PAGESIZE 1000
SET LINESIZE 200
SET FEEDBACK OFF

-- Check what date/timestamp columns exist in COLLECTION_ table
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH
FROM DBA_TAB_COLUMNS
WHERE TABLE_NAME = 'COLLECTION_'
  AND OWNER = 'DESIGN12'
  AND (DATA_TYPE LIKE '%DATE%' OR DATA_TYPE LIKE '%TIME%' OR COLUMN_NAME LIKE '%CREATE%' OR COLUMN_NAME LIKE '%MODIFIED%' OR COLUMN_NAME LIKE '%DATE%' OR COLUMN_NAME LIKE '%TIME%')
ORDER BY COLUMN_ID;

EXIT;
