SET PAGESIZE 100
SET LINESIZE 300
SET FEEDBACK OFF

-- Find all BLOB and CLOB columns in DESIGN12 schema
SELECT
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE
FROM DBA_TAB_COLUMNS
WHERE OWNER = 'DESIGN12'
  AND DATA_TYPE IN ('BLOB', 'CLOB', 'NCLOB')
  AND (TABLE_NAME = 'COLLECTION_'
    OR TABLE_NAME = 'REL_COMMON'
    OR TABLE_NAME LIKE '%PROP%'
    OR TABLE_NAME LIKE '%ATTR%'
    OR TABLE_NAME LIKE '%META%')
ORDER BY TABLE_NAME, COLUMN_NAME;

EXIT;
