SET PAGESIZE 50000
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Check StudyFolder 197647 - which direction is the relationship?
SELECT 
    'Forward (StudyFolder as parent)' as DIRECTION,
    r.FORWARD_OBJECT_ID as PARENT_ID,
    c_parent.CAPTION_S_ as PARENT_NAME,
    r.OBJECT_ID as CHILD_ID,
    c_child.CAPTION_S_ as CHILD_NAME,
    r.REL_TYPE,
    r.SEQ_NUMBER
FROM DESIGN1.REL_COMMON r
INNER JOIN DESIGN1.COLLECTION_ c_parent ON r.FORWARD_OBJECT_ID = c_parent.OBJECT_ID
INNER JOIN DESIGN1.COLLECTION_ c_child ON r.OBJECT_ID = c_child.OBJECT_ID
WHERE r.FORWARD_OBJECT_ID = 197647
ORDER BY r.SEQ_NUMBER;

-- Check reverse (StudyFolder as child)
SELECT 
    'Reverse (StudyFolder as child)' as DIRECTION,
    r.FORWARD_OBJECT_ID as PARENT_ID,
    c_parent.CAPTION_S_ as PARENT_NAME,
    r.OBJECT_ID as CHILD_ID,
    c_child.CAPTION_S_ as CHILD_NAME,
    r.REL_TYPE,
    r.SEQ_NUMBER
FROM DESIGN1.REL_COMMON r
INNER JOIN DESIGN1.COLLECTION_ c_parent ON r.FORWARD_OBJECT_ID = c_parent.OBJECT_ID
INNER JOIN DESIGN1.COLLECTION_ c_child ON r.OBJECT_ID = c_child.OBJECT_ID
WHERE r.OBJECT_ID = 197647
ORDER BY r.SEQ_NUMBER;

-- Check if there are bidirectional relationships
SELECT 
    'Bidirectional check' as INFO,
    r1.FORWARD_OBJECT_ID as ID1,
    r1.OBJECT_ID as ID2,
    r2.FORWARD_OBJECT_ID as ID2_PARENT,
    r2.OBJECT_ID as ID2_CHILD
FROM DESIGN1.REL_COMMON r1
LEFT JOIN DESIGN1.REL_COMMON r2 ON r1.OBJECT_ID = r2.FORWARD_OBJECT_ID AND r1.FORWARD_OBJECT_ID = r2.OBJECT_ID
WHERE r1.FORWARD_OBJECT_ID = 197647
  OR r1.OBJECT_ID = 197647
FETCH FIRST 10 ROWS ONLY;

EXIT;
