SET PAGESIZE 100
SET LINESIZE 250
SET FEEDBACK OFF

-- Get ALL level 1 children including PartInstanceLibrary
SELECT
    r.OBJECT_VERSION_ID,
    r.SEQ_NUMBER,
    r.REL_TYPE,
    c.OBJECT_ID,
    c.CAPTION_S_,
    cd.NICE_NAME AS CLASS_TYPE,
    TO_CHAR(c.MODIFICATIONDATE_DA_, 'DD/MM/YYYY HH24:MI:SS') AS MOD_DATE
FROM DESIGN12.REL_COMMON r
INNER JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18140190
ORDER BY c.CAPTION_S_;

EXIT;
