SET PAGESIZE 50000
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Check a specific StudyFolder (197647) that should have children
SELECT 
    'StudyFolder 197647 Children' as INFO,
    r.FORWARD_OBJECT_ID as PARENT_ID,
    c_parent.CAPTION_S_ as PARENT_NAME,
    r.OBJECT_ID as CHILD_ID,
    c_child.CAPTION_S_ as CHILD_NAME,
    r.REL_TYPE,
    r.SEQ_NUMBER
FROM DESIGN1.REL_COMMON r
INNER JOIN DESIGN1.COLLECTION_ c_parent ON r.FORWARD_OBJECT_ID = c_parent.OBJECT_ID
INNER JOIN DESIGN1.COLLECTION_ c_child ON r.OBJECT_ID = c_child.OBJECT_ID
WHERE r.FORWARD_OBJECT_ID = 197647
ORDER BY r.SEQ_NUMBER;

-- Check what REL_TYPE values exist
SELECT DISTINCT REL_TYPE, COUNT(*) as COUNT
FROM DESIGN1.REL_COMMON
WHERE FORWARD_OBJECT_ID IN (
    SELECT OBJECT_ID FROM DESIGN1.COLLECTION_ 
    WHERE CAPTION_S_ = 'StudyFolder'
    FETCH FIRST 10 ROWS ONLY
)
GROUP BY REL_TYPE
ORDER BY REL_TYPE;

-- Check if StudyFolder children are in our tree data
SELECT 
    'StudyFolder in tree data' as INFO,
    LEVEL,
    PRIOR c.OBJECT_ID as PARENT_ID,
    c.OBJECT_ID,
    c.CAPTION_S_,
    r.SEQ_NUMBER
FROM DESIGN1.REL_COMMON r
INNER JOIN DESIGN1.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
WHERE r.FORWARD_OBJECT_ID = 197647
START WITH r.FORWARD_OBJECT_ID = 60
CONNECT BY NOCYCLE PRIOR r.OBJECT_ID = r.FORWARD_OBJECT_ID
ORDER SIBLINGS BY r.SEQ_NUMBER;

EXIT;
