SET PAGESIZE 100
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Check columns in COLLECTION_ table
SELECT COLUMN_NAME, DATA_TYPE 
FROM DBA_TAB_COLUMNS 
WHERE OWNER = 'DESIGN1' 
  AND TABLE_NAME = 'COLLECTION_'
  AND (COLUMN_NAME LIKE '%CLASS%' OR COLUMN_NAME LIKE '%TYPE%' OR COLUMN_NAME LIKE '%NAME%')
ORDER BY COLUMN_NAME;
EXIT;