SET PAGESIZE 100
SET LINESIZE 300
SET FEEDBACK OFF

-- Check if COLLECTIONS_VR_ correlates with ordering
SELECT
    c.COLLECTIONS_VR_,
    c.OBJECT_ID,
    c.CAPTION_S_,
    r.OBJECT_VERSION_ID,
    TO_CHAR(c.MODIFICATIONDATE_DA_, 'DD/MM/YYYY HH24:MI:SS') AS MOD_DATE
FROM DESIGN12.REL_COMMON r
INNER JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
WHERE r.FORWARD_OBJECT_ID = 18140190
ORDER BY c.COLLECTIONS_VR_, c.OBJECT_ID;

EXIT;
