SET PAGESIZE 100
SET LINESIZE 300
SET FEEDBACK OFF

-- Check the FIELD_NAME column in REL_COMMON
-- This might indicate the type of relationship or ordering
SELECT
    r.FIELD_NAME,
    r.OBJECT_VERSION_ID,
    r.SEQ_NUMBER,
    r.REL_TYPE,
    c.OBJECT_ID,
    c.CAPTION_S_
FROM DESIGN12.REL_COMMON r
INNER JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
WHERE r.FORWARD_OBJECT_ID = 18140190
ORDER BY r.FIELD_NAME, r.OBJECT_VERSION_ID;

-- Also check distinct FIELD_NAME values across the database
SELECT DISTINCT FIELD_NAME, COUNT(*) AS RECORD_COUNT
FROM DESIGN12.REL_COMMON
WHERE FORWARD_OBJECT_ID = 18140190
GROUP BY FIELD_NAME
ORDER BY FIELD_NAME;

EXIT;
