SET PAGESIZE 50000
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Maybe projects are stored differently in DESIGN4?
-- Check if there are any root-level collections
SELECT 
    c.OBJECT_ID,
    c.CAPTION_S_,
    c.NAME_S_,
    (SELECT COUNT(*) FROM DESIGN4.REL_COMMON r WHERE r.FORWARD_OBJECT_ID = c.OBJECT_ID) as CHILD_COUNT,
    (SELECT COUNT(*) FROM DESIGN4.REL_COMMON r WHERE r.OBJECT_ID = c.OBJECT_ID) as PARENT_COUNT
FROM DESIGN4.COLLECTION_ c
WHERE c.OBJECT_ID IN (
    SELECT DISTINCT FORWARD_OBJECT_ID 
    FROM DESIGN4.REL_COMMON
    WHERE FORWARD_OBJECT_ID NOT IN (
        SELECT DISTINCT OBJECT_ID 
        FROM DESIGN4.REL_COMMON 
        WHERE OBJECT_ID IS NOT NULL
    )
)
ORDER BY c.OBJECT_ID;

-- Check all collections
SELECT COUNT(*) as TOTAL_COLLECTIONS FROM DESIGN4.COLLECTION_;

-- Check if DFPROJECT has any structure at all
SELECT * FROM DESIGN4.DFPROJECT;

EXIT;
