SET PAGESIZE 50
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Get all columns in CLASS_DEFINITIONS
SELECT COLUMN_NAME, DATA_TYPE
FROM DBA_TAB_COLUMNS
WHERE OWNER = 'DESIGN12'
  AND TABLE_NAME = 'CLASS_DEFINITIONS'
ORDER BY COLUMN_NAME;
EXIT;