SET PAGESIZE 50000
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Check if there are any collections at all (maybe in a different state)
SELECT COUNT(*) as TOTAL_COLLECTIONS
FROM DESIGN4.COLLECTION_;

-- Check REL_COMMON structure more carefully
SELECT 
    'Relationships' as INFO,
    COUNT(*) as COUNT,
    COUNT(DISTINCT FORWARD_OBJECT_ID) as UNIQUE_PARENTS,
    COUNT(DISTINCT OBJECT_ID) as UNIQUE_CHILDREN
FROM DESIGN4.REL_COMMON;

-- Check what object IDs are in REL_COMMON
SELECT DISTINCT FORWARD_OBJECT_ID as OBJECT_ID, 'Parent' as ROLE
FROM DESIGN4.REL_COMMON
UNION
SELECT DISTINCT OBJECT_ID, 'Child' as ROLE
FROM DESIGN4.REL_COMMON
WHERE OBJECT_ID IS NOT NULL
ORDER BY OBJECT_ID;

-- Check if there are any other tables that might contain project info
SELECT TABLE_NAME
FROM DBA_TABLES
WHERE OWNER = 'DESIGN4'
  AND (TABLE_NAME LIKE '%PROJECT%' OR TABLE_NAME LIKE '%ROOT%' OR TABLE_NAME LIKE '%COLLECTION%')
ORDER BY TABLE_NAME;

EXIT;
