SET PAGESIZE 100
SET LINESIZE 300
SET FEEDBACK OFF

-- Check EMS_CONFIGURATION table structure
SELECT COLUMN_NAME, DATA_TYPE
FROM DBA_TAB_COLUMNS
WHERE TABLE_NAME = 'EMS_CONFIGURATION'
  AND OWNER = 'DESIGN12'
ORDER BY COLUMN_ID;

-- Get all configuration data
SELECT *
FROM DESIGN12.EMS_CONFIGURATION;

EXIT;
