SET PAGESIZE 100
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- List all DF_* tables (these might be customization tables)
SELECT TABLE_NAME
FROM DBA_TABLES
WHERE OWNER = 'DESIGN12'
  AND TABLE_NAME LIKE 'DF_%'
ORDER BY TABLE_NAME;
EXIT;