SET PAGESIZE 100
SET LINESIZE 300
SET FEEDBACK OFF

-- Check what node 18143953 is
SELECT
    c.OBJECT_ID,
    c.CAPTION_S_,
    c.EXTERNALID_S_,
    c.STATUS_S_,
    c.COLLECTIONS_VR_,
    cd.NICE_NAME AS CLASS_TYPE,
    TO_CHAR(c.MODIFICATIONDATE_DA_, 'DD/MM/YYYY HH24:MI:SS') AS MOD_DATE
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE c.OBJECT_ID = 18143953;

-- Get its relationship data
SELECT *
FROM DESIGN12.REL_COMMON
WHERE OBJECT_ID = 18143953;

EXIT;
