SET PAGESIZE 50000
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Check REL_COMMON to see what relationships exist
SELECT 
    r.FORWARD_OBJECT_ID as PARENT_ID,
    r.OBJECT_ID as CHILD_ID,
    c_parent.CAPTION_S_ as PARENT_NAME,
    c_child.CAPTION_S_ as CHILD_NAME
FROM DESIGN4.REL_COMMON r
LEFT JOIN DESIGN4.COLLECTION_ c_parent ON r.FORWARD_OBJECT_ID = c_parent.OBJECT_ID
LEFT JOIN DESIGN4.COLLECTION_ c_child ON r.OBJECT_ID = c_child.OBJECT_ID
ORDER BY r.FORWARD_OBJECT_ID;

-- Find potential root nodes (nodes that are parents but not children)
SELECT 
    c.OBJECT_ID,
    c.CAPTION_S_,
    (SELECT COUNT(*) FROM DESIGN4.REL_COMMON r WHERE r.FORWARD_OBJECT_ID = c.OBJECT_ID) as CHILD_COUNT
FROM DESIGN4.COLLECTION_ c
WHERE c.OBJECT_ID IN (SELECT DISTINCT FORWARD_OBJECT_ID FROM DESIGN4.REL_COMMON)
  AND c.OBJECT_ID NOT IN (SELECT DISTINCT OBJECT_ID FROM DESIGN4.REL_COMMON WHERE OBJECT_ID IS NOT NULL)
ORDER BY c.OBJECT_ID;

EXIT;
