SET PAGESIZE 1000
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Check which instance we're connected to
SELECT INSTANCE_NAME, HOST_NAME, DATABASE_NAME
FROM V$INSTANCE;

-- Check DFPROJECT in DESIGN4 on this instance
SELECT COUNT(*) as ROW_COUNT FROM DESIGN4.DFPROJECT;

-- Check if we can see the table structure
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
FROM DBA_TAB_COLUMNS
WHERE OWNER = 'DESIGN4' AND TABLE_NAME = 'DFPROJECT'
ORDER BY COLUMN_ID;

EXIT;
