SET PAGESIZE 100
SET LINESIZE 200
SET FEEDBACK OFF

-- Check all columns in REL_COMMON table
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH
FROM DBA_TAB_COLUMNS
WHERE TABLE_NAME = 'REL_COMMON'
  AND OWNER = 'DESIGN12'
ORDER BY COLUMN_ID;

-- Check all data for Level 1 children
SELECT *
FROM DESIGN12.REL_COMMON r
WHERE r.FORWARD_OBJECT_ID = 18140190
ORDER BY r.OBJECT_ID;

EXIT;
