SET PAGESIZE 200
SET LINESIZE 300
SET FEEDBACK OFF

-- Get ALL columns from COLLECTION_ table for our level 1 nodes
SELECT COLUMN_NAME, DATA_TYPE
FROM DBA_TAB_COLUMNS
WHERE TABLE_NAME = 'COLLECTION_'
  AND OWNER = 'DESIGN12'
ORDER BY COLUMN_ID;

EXIT;
