SET PAGESIZE 1000
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Check instance
SELECT INSTANCE_NAME, HOST_NAME, DATABASE_NAME
FROM V$INSTANCE;

-- Check DESIGN4.DFPROJECT on THIS instance
SELECT COUNT(*) as ROW_COUNT FROM DESIGN4.DFPROJECT;

-- If there are rows, show them
SELECT 
    p.PROJECTID,
    c.CAPTION_S_,
    c.NAME_S_,
    c.EXTERNALID_S_
FROM DESIGN4.DFPROJECT p
LEFT JOIN DESIGN4.COLLECTION_ c ON p.PROJECTID = c.OBJECT_ID
ORDER BY p.PROJECTID;

EXIT;
