SET PAGESIZE 100
SET LINESIZE 300
SET FEEDBACK OFF

-- Check structure of DFUSERFOLDERTABLE
SELECT COLUMN_NAME, DATA_TYPE
FROM DBA_TAB_COLUMNS
WHERE TABLE_NAME = 'DFUSERFOLDERTABLE'
  AND OWNER = 'DESIGN12'
ORDER BY COLUMN_ID;

-- Check if it contains ordering information for our project
SELECT *
FROM DESIGN12.DFUSERFOLDERTABLE
WHERE ROWNUM <= 20;

EXIT;
