SET PAGESIZE 50000
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Check DESIGN1 COLLECTION_ columns
SELECT 'DESIGN1' as SCHEMA, COLUMN_NAME, DATA_TYPE
FROM DBA_TAB_COLUMNS
WHERE OWNER = 'DESIGN1' AND TABLE_NAME = 'COLLECTION_' AND COLUMN_NAME LIKE '%NAME%'
ORDER BY COLUMN_NAME;

-- Check DESIGN4 COLLECTION_ columns  
SELECT 'DESIGN4' as SCHEMA, COLUMN_NAME, DATA_TYPE
FROM DBA_TAB_COLUMNS
WHERE OWNER = 'DESIGN4' AND TABLE_NAME = 'COLLECTION_' AND COLUMN_NAME LIKE '%NAME%'
ORDER BY COLUMN_NAME;

-- Check if DESIGN4 has NAME1_S_ at all
SELECT COLUMN_NAME
FROM DBA_TAB_COLUMNS
WHERE OWNER = 'DESIGN4' AND TABLE_NAME = 'COLLECTION_' AND COLUMN_NAME = 'NAME1_S_';

EXIT;
