SET PAGESIZE 200
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING OFF

-- Get all TYPE_IDs that have icons
SELECT DISTINCT TO_CHAR(di.TYPE_ID)
FROM DESIGN12.DF_ICONS_DATA di
WHERE di.CLASS_IMAGE IS NOT NULL
ORDER BY di.TYPE_ID;
EXIT;