SET PAGESIZE 100
SET LINESIZE 300
SET FEEDBACK OFF

-- Check if COLLECTION_ has any order-related columns
SELECT COLUMN_NAME, DATA_TYPE
FROM DBA_TAB_COLUMNS
WHERE TABLE_NAME = 'COLLECTION_'
  AND OWNER = 'DESIGN12'
  AND (COLUMN_NAME LIKE '%ORDER%'
    OR COLUMN_NAME LIKE '%SEQ%'
    OR COLUMN_NAME LIKE '%INDEX%'
    OR COLUMN_NAME LIKE '%POSITION%'
    OR COLUMN_NAME LIKE '%SORT%')
ORDER BY COLUMN_NAME;

-- Also check for any other relationship tables
SELECT TABLE_NAME
FROM DBA_TABLES
WHERE OWNER = 'DESIGN12'
  AND (TABLE_NAME LIKE '%REL%' OR TABLE_NAME LIKE '%ORDER%' OR TABLE_NAME LIKE '%SEQ%')
ORDER BY TABLE_NAME;

EXIT;
