SET PAGESIZE 50000
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Compare DFPROJECT
SELECT 'DESIGN1' as SCHEMA, COUNT(*) as PROJECT_COUNT FROM DESIGN1.DFPROJECT
UNION ALL
SELECT 'DESIGN4' as SCHEMA, COUNT(*) as PROJECT_COUNT FROM DESIGN4.DFPROJECT;

-- Compare COLLECTION_
SELECT 'DESIGN1' as SCHEMA, COUNT(*) as COLLECTION_COUNT FROM DESIGN1.COLLECTION_
UNION ALL
SELECT 'DESIGN4' as SCHEMA, COUNT(*) as COLLECTION_COUNT FROM DESIGN4.COLLECTION_;

-- Check if DESIGN4 has any data in key tables
SELECT 'DFPROJECT' as TABLE_NAME, COUNT(*) as ROW_COUNT FROM DESIGN4.DFPROJECT
UNION ALL
SELECT 'COLLECTION_' as TABLE_NAME, COUNT(*) as ROW_COUNT FROM DESIGN4.COLLECTION_
UNION ALL
SELECT 'REL_COMMON' as TABLE_NAME, COUNT(*) as ROW_COUNT FROM DESIGN4.REL_COMMON
UNION ALL
SELECT 'DFPROJECTLOCK' as TABLE_NAME, COUNT(*) as ROW_COUNT FROM DESIGN4.DFPROJECTLOCK
UNION ALL
SELECT 'DFSESSION' as TABLE_NAME, COUNT(*) as ROW_COUNT FROM DESIGN4.DFSESSION;

EXIT;
