SET PAGESIZE 50000
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Check if DESIGN4 schema exists and is active
SELECT USERNAME, ACCOUNT_STATUS, CREATED
FROM DBA_USERS
WHERE USERNAME = 'DESIGN4';

-- Check table count in DESIGN4
SELECT COUNT(*) as TABLE_COUNT
FROM DBA_TABLES
WHERE OWNER = 'DESIGN4';

-- Check if DFPROJECT table exists
SELECT TABLE_NAME, NUM_ROWS, LAST_ANALYZED
FROM DBA_TABLES
WHERE OWNER = 'DESIGN4' AND TABLE_NAME = 'DFPROJECT';

-- Check if COLLECTION_ table exists and has data
SELECT COUNT(*) as COLLECTION_COUNT, 
       MIN(OBJECT_ID) as MIN_ID, 
       MAX(OBJECT_ID) as MAX_ID
FROM DESIGN4.COLLECTION_;

-- Check REL_COMMON table
SELECT COUNT(*) as REL_COUNT
FROM DESIGN4.REL_COMMON;

-- Check for any collections that might be root nodes
SELECT COUNT(*) as ROOT_CANDIDATES
FROM DESIGN4.COLLECTION_ c
WHERE c.OBJECT_ID IN (
    SELECT DISTINCT FORWARD_OBJECT_ID 
    FROM DESIGN4.REL_COMMON
    WHERE FORWARD_OBJECT_ID NOT IN (SELECT DISTINCT OBJECT_ID FROM DESIGN4.REL_COMMON WHERE OBJECT_ID IS NOT NULL)
);

EXIT;
