SET PAGESIZE 50000
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Check all tables in DESIGN4 and their row counts
SELECT 
    TABLE_NAME,
    NUM_ROWS,
    LAST_ANALYZED
FROM DBA_TABLES
WHERE OWNER = 'DESIGN4'
ORDER BY NUM_ROWS DESC NULLS LAST, TABLE_NAME
FETCH FIRST 30 ROWS ONLY;

-- Check DFPROJECT table structure and actual data
SELECT COUNT(*) as ROW_COUNT FROM DESIGN4.DFPROJECT;

-- Check if DFPROJECT has any columns
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH
FROM DBA_TAB_COLUMNS
WHERE OWNER = 'DESIGN4' AND TABLE_NAME = 'DFPROJECT'
ORDER BY COLUMN_ID;

-- Check COLLECTION_ table structure
SELECT COUNT(*) as ROW_COUNT FROM DESIGN4.COLLECTION_;

-- Check COLLECTION_ columns
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH
FROM DBA_TAB_COLUMNS
WHERE OWNER = 'DESIGN4' AND TABLE_NAME = 'COLLECTION_'
ORDER BY COLUMN_ID
FETCH FIRST 20 ROWS ONLY;

-- Check REL_COMMON in detail
SELECT * FROM DESIGN4.REL_COMMON;

EXIT;
