SET PAGESIZE 20
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Check if there are any tables with 'ICON' in the name
SELECT TABLE_NAME
FROM DBA_TABLES
WHERE OWNER = 'DESIGN12'
  AND (TABLE_NAME LIKE '%ICON%' OR TABLE_NAME LIKE '%IMAGE%' OR TABLE_NAME LIKE '%PICTURE%')
ORDER BY TABLE_NAME;
EXIT;