SET PAGESIZE 20
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Check CLASS_DEFINITIONS table structure for icon-related columns
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH
FROM DBA_TAB_COLUMNS
WHERE OWNER = 'DESIGN12'
  AND TABLE_NAME = 'CLASS_DEFINITIONS'
  AND (COLUMN_NAME LIKE '%ICON%' OR COLUMN_NAME LIKE '%IMAGE%' OR COLUMN_NAME LIKE '%PICTURE%' OR COLUMN_NAME LIKE '%FILE%')
ORDER BY COLUMN_NAME;
EXIT;