SET PAGESIZE 50
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Check if there's a filename or path column in DF_ICONS_DATA or related tables
SELECT 
    'DF_ICONS_DATA' AS TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE
FROM DBA_TAB_COLUMNS
WHERE OWNER = 'DESIGN12'
  AND TABLE_NAME = 'DF_ICONS_DATA'
UNION ALL
SELECT 
    'CLASS_DEFINITIONS' AS TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE
FROM DBA_TAB_COLUMNS
WHERE OWNER = 'DESIGN12'
  AND TABLE_NAME = 'CLASS_DEFINITIONS'
  AND (UPPER(COLUMN_NAME) LIKE '%FILE%' OR UPPER(COLUMN_NAME) LIKE '%NAME%' OR UPPER(COLUMN_NAME) LIKE '%PATH%')
ORDER BY TABLE_NAME, COLUMN_NAME;
EXIT;