SET PAGESIZE 30
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Check LV_ICON_ table structure
SELECT COLUMN_NAME, DATA_TYPE
FROM DBA_TAB_COLUMNS
WHERE OWNER = 'DESIGN12'
  AND TABLE_NAME = 'LV_ICON_'
ORDER BY COLUMN_NAME;
EXIT;