SET PAGESIZE 50
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Get sample data from DF_ICONS_DATA
SELECT *
FROM (
    SELECT * FROM DESIGN12.DF_ICONS_DATA
    ORDER BY ROWNUM
)
WHERE ROWNUM <= 20;
EXIT;