SET PAGESIZE 30
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Check structure of DF_ICONS_DATA
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH
FROM DBA_TAB_COLUMNS
WHERE OWNER = 'DESIGN12'
  AND TABLE_NAME = 'DF_ICONS_DATA'
ORDER BY COLUMN_NAME;
EXIT;