SET PAGESIZE 50
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Check COLLECTION_ table for any icon/image related columns
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH
FROM DBA_TAB_COLUMNS
WHERE OWNER = 'DESIGN12'
  AND TABLE_NAME = 'COLLECTION_'
  AND (UPPER(COLUMN_NAME) LIKE '%ICON%' 
       OR UPPER(COLUMN_NAME) LIKE '%IMAGE%' 
       OR UPPER(COLUMN_NAME) LIKE '%PICTURE%'
       OR UPPER(COLUMN_NAME) LIKE '%FILE%'
       OR UPPER(COLUMN_NAME) LIKE '%PATH%'
       OR UPPER(COLUMN_NAME) LIKE '%NAME%'
       OR UPPER(COLUMN_NAME) LIKE '%CAPTION%')
ORDER BY COLUMN_NAME;
EXIT;