SET PAGESIZE 100
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Find all tables with icon/image/picture in name
SELECT TABLE_NAME
FROM DBA_TABLES
WHERE OWNER = 'DESIGN12'
  AND (UPPER(TABLE_NAME) LIKE '%ICON%' 
       OR UPPER(TABLE_NAME) LIKE '%IMAGE%' 
       OR UPPER(TABLE_NAME) LIKE '%PICTURE%'
       OR UPPER(TABLE_NAME) LIKE '%GRAPHIC%'
       OR UPPER(TABLE_NAME) LIKE '%BITMAP%')
ORDER BY TABLE_NAME;
EXIT;