SET PAGESIZE 100
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Find all columns with icon/image/picture in name
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE
FROM DBA_TAB_COLUMNS
WHERE OWNER = 'DESIGN12'
  AND (UPPER(COLUMN_NAME) LIKE '%ICON%' 
       OR UPPER(COLUMN_NAME) LIKE '%IMAGE%' 
       OR UPPER(COLUMN_NAME) LIKE '%PICTURE%'
       OR UPPER(COLUMN_NAME) LIKE '%GRAPHIC%'
       OR UPPER(COLUMN_NAME) LIKE '%BITMAP%'
       OR UPPER(COLUMN_NAME) LIKE '%FILE%'
       OR UPPER(COLUMN_NAME) LIKE '%PATH%')
ORDER BY TABLE_NAME, COLUMN_NAME;
EXIT;