SET PAGESIZE 5
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING OFF

-- Test icon extraction for a few types
SELECT 
    di.TYPE_ID || '|' ||
    LENGTH(di.CLASS_IMAGE) || '|' ||
    SUBSTR(UTL_ENCODE.BASE64_ENCODE(di.CLASS_IMAGE), 1, 100)
FROM DESIGN12.DF_ICONS_DATA di
WHERE di.CLASS_IMAGE IS NOT NULL
  AND di.TYPE_ID IN (18, 45, 46, 64)
ORDER BY di.TYPE_ID;
EXIT;