SET PAGESIZE 1
SET LINESIZE 10000
SET LONG 10000
SET FEEDBACK OFF
SET HEADING OFF

-- Get icon for TYPE_ID 64 (PmProject) with full base64
SELECT 
    '64|' ||
    LENGTH(di.CLASS_IMAGE) || '|' ||
    UTL_ENCODE.BASE64_ENCODE(di.CLASS_IMAGE)
FROM DESIGN12.DF_ICONS_DATA di
WHERE di.TYPE_ID = 64
  AND di.CLASS_IMAGE IS NOT NULL;
EXIT;