SET PAGESIZE 1
SET LINESIZE 5000
SET FEEDBACK OFF
SET HEADING OFF

-- Test extraction for TYPE_ID 72
SELECT 
    '72|' ||
    LENGTH(di.CLASS_IMAGE) || '|' ||
    UTL_ENCODE.BASE64_ENCODE(di.CLASS_IMAGE)
FROM DESIGN12.DF_ICONS_DATA di
WHERE di.TYPE_ID = 72
  AND di.CLASS_IMAGE IS NOT NULL;
EXIT;