SET PAGESIZE 100
SET LINESIZE 300
SET FEEDBACK OFF

-- Get complete information about all Level 1 children
-- with all possible ordering fields
SELECT
    c.CAPTION_S_,
    c.OBJECT_ID,
    r.OBJECT_VERSION_ID,
    r.SEQ_NUMBER,
    r.REL_TYPE,
    r.FIELD_NAME,
    r.CLASS_ID AS REL_CLASS_ID,
    TO_CHAR(c.MODIFICATIONDATE_DA_, 'DD/MM/YYYY HH24:MI:SS') AS MOD_DATE,
    cd.NICE_NAME AS CLASS_TYPE
FROM DESIGN12.REL_COMMON r
INNER JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18140190
ORDER BY c.CAPTION_S_;

EXIT;
