SET PAGESIZE 100
SET LINESIZE 200
SET FEEDBACK OFF

-- Search for tables that might store UI preferences or custom orderings
SELECT TABLE_NAME, NUM_ROWS
FROM DBA_TABLES
WHERE OWNER = 'DESIGN12'
  AND (TABLE_NAME LIKE '%PREF%'
    OR TABLE_NAME LIKE '%UI%'
    OR TABLE_NAME LIKE '%VIEW%'
    OR TABLE_NAME LIKE '%DISPLAY%'
    OR TABLE_NAME LIKE '%ORDER%'
    OR TABLE_NAME LIKE '%SORT%'
    OR TABLE_NAME LIKE '%USER%')
ORDER BY TABLE_NAME;

EXIT;
