SET PAGESIZE 100
SET LINESIZE 300
SET FEEDBACK OFF

-- Try to find this node in COLLECTION_ with all filters removed
SELECT
    c.OBJECT_ID,
    c.CAPTION_S_,
    c.STATUS_S_,
    c.NAME_S_,
    c.EXTERNALID_S_,
    cd.NICE_NAME AS CLASS_TYPE
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE c.OBJECT_ID = 18143953;

-- If not found, check if it's been deleted or archived
SELECT COUNT(*)
FROM DESIGN12.COLLECTION_
WHERE OBJECT_ID = 18143953;

EXIT;
