SET PAGESIZE 100
SET LINESIZE 300
SET FEEDBACK OFF

-- Search for PartInstanceLibrary with various spellings
SELECT
    c.OBJECT_ID,
    c.CAPTION_S_,
    c.NAME_S_,
    c.STATUS_S_,
    cd.NICE_NAME AS CLASS_TYPE,
    r.FORWARD_OBJECT_ID AS PARENT_ID
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
LEFT JOIN DESIGN12.REL_COMMON r ON c.OBJECT_ID = r.OBJECT_ID
WHERE (c.CAPTION_S_ LIKE '%PartInstance%'
    OR c.NAME_S_ LIKE '%PartInstance%'
    OR c.CAPTION_S_ = 'PartInstanceLibrary')
  AND ROWNUM <= 20;

-- Also search in all projects for this name
SELECT
    c.OBJECT_ID,
    c.CAPTION_S_,
    r.FORWARD_OBJECT_ID AS PARENT_ID,
    p.CAPTION_S_ AS PARENT_NAME
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.REL_COMMON r ON c.OBJECT_ID = r.OBJECT_ID
LEFT JOIN DESIGN12.COLLECTION_ p ON r.FORWARD_OBJECT_ID = p.OBJECT_ID
WHERE c.CAPTION_S_ = 'PartInstanceLibrary';

EXIT;
