SET PAGESIZE 500
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING OFF

-- Get all unique class names used in collections
SELECT DISTINCT cd.NAME
FROM DESIGN12.COLLECTION_ c
INNER JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
ORDER BY cd.NAME;
EXIT;