SET PAGESIZE 100
SET LINESIZE 300
SET FEEDBACK OFF

-- Get ALL relationships for project 18140190, even if COLLECTION_ data is missing
-- This will show us the ghost node 18143953
SELECT
    r.OBJECT_ID,
    r.OBJECT_VERSION_ID,
    r.SEQ_NUMBER,
    c.CAPTION_S_,
    c.STATUS_S_,
    cd.NICE_NAME AS CLASS_TYPE
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18140190
ORDER BY r.OBJECT_VERSION_ID;

EXIT;
