SET PAGESIZE 100
SET LINESIZE 300
SET FEEDBACK OFF

-- Check if USER_FOLDER_ID relates to our collections
-- and if there's ordering information
SELECT
    uft.USER_ID,
    uft.PROJECT_ID,
    uft.USER_FOLDER_ID,
    c.CAPTION_S_,
    c.OBJECT_ID,
    cd.NICE_NAME AS CLASS_TYPE
FROM DESIGN12.DFUSERFOLDERTABLE uft
LEFT JOIN DESIGN12.COLLECTION_ c ON uft.USER_FOLDER_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE uft.PROJECT_ID = 18140190
ORDER BY uft.USER_ID, uft.USER_FOLDER_ID;

-- Also check if there's a relationship between USER_FOLDER_ID and our level 1 children
SELECT
    uft.USER_FOLDER_ID,
    c_uf.CAPTION_S_ AS USERFOLDER_NAME,
    r.OBJECT_ID AS CHILD_ID,
    c_child.CAPTION_S_ AS CHILD_NAME
FROM DESIGN12.DFUSERFOLDERTABLE uft
LEFT JOIN DESIGN12.COLLECTION_ c_uf ON uft.USER_FOLDER_ID = c_uf.OBJECT_ID
LEFT JOIN DESIGN12.REL_COMMON r ON uft.USER_FOLDER_ID = r.FORWARD_OBJECT_ID
LEFT JOIN DESIGN12.COLLECTION_ c_child ON r.OBJECT_ID = c_child.OBJECT_ID
WHERE uft.PROJECT_ID = 18140190
  AND ROWNUM <= 50
ORDER BY uft.USER_FOLDER_ID, r.OBJECT_ID;

EXIT;
