SET PAGESIZE 100
SET LINESIZE 300
SET FEEDBACK OFF

-- Get ALL level 1 children including those with any status
SELECT
    r.OBJECT_VERSION_ID,
    c.OBJECT_ID,
    c.CAPTION_S_,
    c.STATUS_S_,
    cd.NICE_NAME AS CLASS_TYPE,
    TO_CHAR(c.MODIFICATIONDATE_DA_, 'DD/MM/YYYY HH24:MI:SS') AS MOD_DATE
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18140190
ORDER BY r.OBJECT_VERSION_ID;

EXIT;
