SET PAGESIZE 10
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Sample: Get collection with class name
SELECT c.OBJECT_ID, c.CAPTION_S_, c.CLASS_ID, cd.CLASS_NAME
FROM DESIGN1.COLLECTION_ c
LEFT JOIN DESIGN1.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.CLASS_ID
WHERE ROWNUM <= 10;
EXIT;