SET PAGESIZE 20
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING ON

-- Get sample class definitions
SELECT * FROM (
  SELECT CLASS_ID, CLASS_NAME 
  FROM DESIGN1.CLASS_DEFINITIONS 
  ORDER BY CLASS_ID
) WHERE ROWNUM <= 20;
EXIT;