SET PAGESIZE 100
SET LINESIZE 200
SET FEEDBACK OFF

-- Search for tables that might store properties or attributes
SELECT TABLE_NAME, NUM_ROWS
FROM DBA_TABLES
WHERE OWNER = 'DESIGN12'
  AND (TABLE_NAME LIKE '%PROP%'
    OR TABLE_NAME LIKE '%ATTR%'
    OR TABLE_NAME LIKE '%META%'
    OR TABLE_NAME LIKE '%CONFIG%'
    OR TABLE_NAME LIKE '%SETTING%')
ORDER BY TABLE_NAME;

EXIT;
