SET PAGESIZE 100
SET LINESIZE 200
SET FEEDBACK OFF

-- Search for views that might contain ordering logic
SELECT VIEW_NAME
FROM DBA_VIEWS
WHERE OWNER = 'DESIGN12'
  AND (VIEW_NAME LIKE '%ORDER%'
    OR VIEW_NAME LIKE '%COLLECT%'
    OR VIEW_NAME LIKE '%TREE%'
    OR VIEW_NAME LIKE '%NAVIG%'
    OR VIEW_NAME LIKE '%CHILD%')
ORDER BY VIEW_NAME;

EXIT;
