SET PAGESIZE 100
SET LINESIZE 200
SET FEEDBACK OFF

-- Search for stored procedures or functions that might handle ordering
SELECT OBJECT_NAME, OBJECT_TYPE
FROM DBA_OBJECTS
WHERE OWNER = 'DESIGN12'
  AND OBJECT_TYPE IN ('PROCEDURE', 'FUNCTION', 'PACKAGE')
  AND (OBJECT_NAME LIKE '%ORDER%'
    OR OBJECT_NAME LIKE '%CHILD%'
    OR OBJECT_NAME LIKE '%TREE%'
    OR OBJECT_NAME LIKE '%COLLECT%'
    OR OBJECT_NAME LIKE '%NAVIG%')
ORDER BY OBJECT_TYPE, OBJECT_NAME;

EXIT;
