SET PAGESIZE 100
SET LINESIZE 200
SET FEEDBACK OFF

-- Find all tables with REL in the name
SELECT TABLE_NAME, NUM_ROWS
FROM DBA_TABLES
WHERE OWNER = 'DESIGN12'
  AND TABLE_NAME LIKE '%REL%'
ORDER BY TABLE_NAME;

EXIT;
