SET PAGESIZE 1000
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING OFF

-- First, try DFPROJECT table (standard approach)
SELECT 
    p.PROJECTID || '|' ||
    NVL(c.CAPTION_S_, 'Unnamed Project') || '|' ||
    NVL(c.CAPTION_S_, 'Unnamed Project') || '|' ||
    NVL(c.EXTERNALID_S_, '')
FROM DESIGN4.DFPROJECT p
LEFT JOIN DESIGN4.COLLECTION_ c ON p.PROJECTID = c.OBJECT_ID
WHERE p.PROJECTID IS NOT NULL
UNION ALL
-- Fallback: If DFPROJECT is empty, look for root collections
SELECT 
    c.OBJECT_ID || '|' ||
    NVL(c.CAPTION_S_, 'Unnamed Project') || '|' ||
    NVL(c.CAPTION_S_, 'Unnamed Project') || '|' ||
    NVL(c.EXTERNALID_S_, '')
FROM DESIGN4.COLLECTION_ c
WHERE c.OBJECT_ID IN (
    SELECT DISTINCT FORWARD_OBJECT_ID 
    FROM DESIGN4.REL_COMMON
    WHERE FORWARD_OBJECT_ID NOT IN (
        SELECT DISTINCT OBJECT_ID 
        FROM DESIGN4.REL_COMMON 
        WHERE OBJECT_ID IS NOT NULL
    )
)
  AND NOT EXISTS (SELECT 1 FROM DESIGN4.DFPROJECT WHERE PROJECTID IS NOT NULL)
ORDER BY 2;
EXIT;
