SET PAGESIZE 1000
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING OFF

SELECT 
    p.PROJECTID || '|' ||
    NVL(c.CAPTION_S_, c.NAME1_S_) || '|' ||
    NVL(c.NAME1_S_, c.CAPTION_S_) || '|' ||
    NVL(c.EXTERNALID_S_, '')
FROM DESIGN4.DFPROJECT p
LEFT JOIN DESIGN4.COLLECTION_ c ON p.PROJECTID = c.OBJECT_ID
ORDER BY c.CAPTION_S_;
EXIT;
