SET PAGESIZE 50000
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING OFF

-- Test the StudyFolder query part
-- Level 0: Root
SELECT '0|0|60|J7337_Rosslyn|J7337_Rosslyn|PP-DESIGN2-24-3-2016-16-15-7-0-60|0' 
FROM DESIGN1.COLLECTION_ c
WHERE c.OBJECT_ID = 60;

-- Level 1: Direct children
SELECT 
    '1|60|' || c.OBJECT_ID || '|' || 
    NVL(c.CAPTION_S_, c.NAME1_S_) || '|' ||
    NVL(c.NAME1_S_, c.CAPTION_S_) || '|' ||
    NVL(c.EXTERNALID_S_, '') || '|' ||
    TO_CHAR(r.SEQ_NUMBER)
FROM DESIGN1.REL_COMMON r
INNER JOIN DESIGN1.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
WHERE r.FORWARD_OBJECT_ID = 60
ORDER BY r.SEQ_NUMBER
FETCH FIRST 5 ROWS ONLY;

-- Level 2+: Hierarchical query
SELECT 
    LEVEL || '|' ||
    PRIOR c.OBJECT_ID || '|' ||
    c.OBJECT_ID || '|' ||
    NVL(c.CAPTION_S_, c.NAME1_S_) || '|' ||
    NVL(c.NAME1_S_, c.CAPTION_S_) || '|' ||
    NVL(c.EXTERNALID_S_, '') || '|' ||
    TO_CHAR(r.SEQ_NUMBER)
FROM DESIGN1.REL_COMMON r
INNER JOIN DESIGN1.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
START WITH r.FORWARD_OBJECT_ID = 60
CONNECT BY NOCYCLE PRIOR r.OBJECT_ID = r.FORWARD_OBJECT_ID
ORDER SIBLINGS BY r.SEQ_NUMBER
FETCH FIRST 10 ROWS ONLY;

-- Test StudyFolder children query
WITH studyfolder_levels AS (
    SELECT 
        c.OBJECT_ID as STUDYFOLDER_ID,
        LEVEL as SF_LEVEL
    FROM DESIGN1.REL_COMMON r
    INNER JOIN DESIGN1.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
    WHERE c.CAPTION_S_ = 'StudyFolder'
    START WITH r.FORWARD_OBJECT_ID = 60
    CONNECT BY NOCYCLE PRIOR r.OBJECT_ID = r.FORWARD_OBJECT_ID
)
SELECT 
    (sf.SF_LEVEL + 1) || '|' ||
    r.FORWARD_OBJECT_ID || '|' ||
    r.OBJECT_ID || '|' ||
    NVL(c.CAPTION_S_, c.NAME1_S_) || '|' ||
    NVL(c.NAME1_S_, c.CAPTION_S_) || '|' ||
    NVL(c.EXTERNALID_S_, '') || '|' ||
    TO_CHAR(r.SEQ_NUMBER)
FROM DESIGN1.REL_COMMON r
INNER JOIN DESIGN1.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
INNER JOIN studyfolder_levels sf ON r.FORWARD_OBJECT_ID = sf.STUDYFOLDER_ID
ORDER BY r.FORWARD_OBJECT_ID, r.SEQ_NUMBER
FETCH FIRST 10 ROWS ONLY;

EXIT;
