SET PAGESIZE 1000
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING OFF

SELECT USERNAME 
FROM DBA_USERS 
WHERE ACCOUNT_STATUS = 'OPEN' 
  AND USERNAME LIKE 'DESIGN%'
  AND USERNAME NOT LIKE '%_AQ'
ORDER BY USERNAME;
EXIT;