SET PAGESIZE 50
SET LINESIZE 200
SET FEEDBACK OFF

-- Sample some nodes from a project to see OBJECT_ID vs MODIFICATIONDATE_DA_
SELECT
    c.OBJECT_ID,
    c.CAPTION_S_,
    TO_CHAR(c.MODIFICATIONDATE_DA_, 'YYYY-MM-DD HH24:MI:SS') AS MODIFICATION_DATE,
    r.SEQ_NUMBER
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.REL_COMMON r ON c.OBJECT_ID = r.OBJECT_ID
WHERE c.OBJECT_ID IN (
    SELECT c2.OBJECT_ID
    FROM DESIGN12.REL_COMMON r2
    INNER JOIN DESIGN12.COLLECTION_ c2 ON r2.OBJECT_ID = c2.OBJECT_ID
    WHERE r2.FORWARD_OBJECT_ID = 18140190
    AND ROWNUM <= 20
)
ORDER BY c.OBJECT_ID;

EXIT;
