SET PAGESIZE 1
SET LINESIZE 32767
SET LONG 1000000
SET LONGCHUNKSIZE 1000000
SET FEEDBACK OFF
SET HEADING OFF

-- Test: Get raw BLOB data type info
SELECT 
    'TYPE_ID: ' || di.TYPE_ID || ' | ' ||
    'BLOB Length: ' || LENGTH(di.CLASS_IMAGE) || ' | ' ||
    'First 4 bytes (hex): ' || RAWTOHEX(SUBSTR(di.CLASS_IMAGE, 1, 4))
FROM DESIGN12.DF_ICONS_DATA di
WHERE di.TYPE_ID = 64
  AND di.CLASS_IMAGE IS NOT NULL;
EXIT;