SET PAGESIZE 1000
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING OFF

-- Get ALL open user schemas (exclude system schemas)
SELECT USERNAME 
FROM DBA_USERS 
WHERE ACCOUNT_STATUS = 'OPEN'
  AND USERNAME NOT IN ('ANONYMOUS', 'APPQOSSYS', 'AUDSYS', 'DBSNMP', 'DIP', 
                       'GSMADMIN_INTERNAL', 'GSMCATUSER', 'GSMUSER', 
                       'ORACLE_OCM', 'OUTLN', 'SYS', 'SYSBACKUP', 'SYSDG', 
                       'SYSKM', 'SYSTEM', 'XDB', 'XS$NULL')
  AND USERNAME NOT LIKE '%_AQ'
ORDER BY USERNAME;
EXIT;