SET PAGESIZE 1
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING OFF

-- Test root node query
SELECT '0|0|18140190|FORD_DEARBORN|FORD_DEARBORN|' || NVL(c.EXTERNALID_S_, '') || '|0|' || NVL(cd.NAME, 'class PmNode') || '|' || NVL(cd.NICE_NAME, 'Unknown') || '|' || TO_CHAR(cd.TYPE_ID)
FROM DESIGN12.COLLECTION_ c
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE c.OBJECT_ID = 18140190;
EXIT;