SET PAGESIZE 100
SET LINESIZE 300
SET FEEDBACK OFF

-- Try OBJECT_VERSION_ID in descending order
SELECT
    r.OBJECT_VERSION_ID,
    r.OBJECT_ID,
    c.CAPTION_S_
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
WHERE r.FORWARD_OBJECT_ID = 18140190
ORDER BY r.OBJECT_VERSION_ID DESC;

-- Also try ordering by OBJECT_ID descending
SELECT
    r.OBJECT_ID,
    r.OBJECT_VERSION_ID,
    c.CAPTION_S_
FROM DESIGN12.REL_COMMON r
LEFT JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
WHERE r.FORWARD_OBJECT_ID = 18140190
ORDER BY r.OBJECT_ID DESC;

EXIT;
