SET PAGESIZE 100
SET LINESIZE 300
SET FEEDBACK OFF

-- Try ordering by CLASS_TYPE, then alphabetically
-- This might match Siemens logic
SELECT
    c.CAPTION_S_,
    cd.NICE_NAME AS CLASS_TYPE,
    c.OBJECT_ID,
    TO_CHAR(c.MODIFICATIONDATE_DA_, 'DD/MM/YYYY HH24:MI:SS') AS MOD_DATE
FROM DESIGN12.REL_COMMON r
INNER JOIN DESIGN12.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
LEFT JOIN DESIGN12.CLASS_DEFINITIONS cd ON c.CLASS_ID = cd.TYPE_ID
WHERE r.FORWARD_OBJECT_ID = 18140190
ORDER BY
    CASE cd.NICE_NAME
        WHEN 'Collection' THEN 1
        WHEN 'RobcadResourceLibrary' THEN 2
        WHEN 'PartLibrary' THEN 3
        WHEN 'MfgLibrary' THEN 4
        ELSE 5
    END,
    c.CAPTION_S_;

EXIT;
