SET PAGESIZE 10000
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING OFF

-- Get 4 levels of navigation tree for J7337_Rosslyn
-- Output format: LEVEL|PARENT_ID|OBJECT_ID|CAPTION|NAME|EXTERNAL_ID

-- Level 0: Root
SELECT '0|0|60|J7337_Rosslyn|J7337_Rosslyn|PP-DESIGN2-24-3-2016-16-15-7-0-60' FROM DUAL;

-- Level 1: Direct children
SELECT 
    '1|60|' || c.OBJECT_ID || '|' || 
    NVL(c.CAPTION_S_, c.NAME1_S_) || '|' ||
    NVL(c.NAME1_S_, c.CAPTION_S_) || '|' ||
    NVL(c.EXTERNALID_S_, '')
FROM DESIGN1.REL_COMMON r
INNER JOIN DESIGN1.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
WHERE r.FORWARD_OBJECT_ID = 60
ORDER BY r.SEQ_NUMBER, c.CAPTION_S_;

-- Level 2: Grandchildren
SELECT 
    '2|' || c1.OBJECT_ID || '|' || c2.OBJECT_ID || '|' ||
    NVL(c2.CAPTION_S_, c2.NAME1_S_) || '|' ||
    NVL(c2.NAME1_S_, c2.CAPTION_S_) || '|' ||
    NVL(c2.EXTERNALID_S_, '')
FROM DESIGN1.REL_COMMON r1
INNER JOIN DESIGN1.COLLECTION_ c1 ON r1.OBJECT_ID = c1.OBJECT_ID
INNER JOIN DESIGN1.REL_COMMON r2 ON r2.FORWARD_OBJECT_ID = c1.OBJECT_ID
INNER JOIN DESIGN1.COLLECTION_ c2 ON r2.OBJECT_ID = c2.OBJECT_ID
WHERE r1.FORWARD_OBJECT_ID = 60
ORDER BY c1.CAPTION_S_, c2.CAPTION_S_;

-- Level 3: Great-grandchildren
SELECT 
    '3|' || c2.OBJECT_ID || '|' || c3.OBJECT_ID || '|' ||
    NVL(c3.CAPTION_S_, c3.NAME1_S_) || '|' ||
    NVL(c3.NAME1_S_, c3.CAPTION_S_) || '|' ||
    NVL(c3.EXTERNALID_S_, '')
FROM DESIGN1.REL_COMMON r1
INNER JOIN DESIGN1.COLLECTION_ c1 ON r1.OBJECT_ID = c1.OBJECT_ID
INNER JOIN DESIGN1.REL_COMMON r2 ON r2.FORWARD_OBJECT_ID = c1.OBJECT_ID
INNER JOIN DESIGN1.COLLECTION_ c2 ON r2.OBJECT_ID = c2.OBJECT_ID
INNER JOIN DESIGN1.REL_COMMON r3 ON r3.FORWARD_OBJECT_ID = c2.OBJECT_ID
INNER JOIN DESIGN1.COLLECTION_ c3 ON r3.OBJECT_ID = c3.OBJECT_ID
WHERE r1.FORWARD_OBJECT_ID = 60
ORDER BY c1.CAPTION_S_, c2.CAPTION_S_, c3.CAPTION_S_;

-- Level 4: Great-great-grandchildren
SELECT 
    '4|' || c3.OBJECT_ID || '|' || c4.OBJECT_ID || '|' ||
    NVL(c4.CAPTION_S_, c4.NAME1_S_) || '|' ||
    NVL(c4.NAME1_S_, c4.CAPTION_S_) || '|' ||
    NVL(c4.EXTERNALID_S_, '')
FROM DESIGN1.REL_COMMON r1
INNER JOIN DESIGN1.COLLECTION_ c1 ON r1.OBJECT_ID = c1.OBJECT_ID
INNER JOIN DESIGN1.REL_COMMON r2 ON r2.FORWARD_OBJECT_ID = c1.OBJECT_ID
INNER JOIN DESIGN1.COLLECTION_ c2 ON r2.OBJECT_ID = c2.OBJECT_ID
INNER JOIN DESIGN1.REL_COMMON r3 ON r3.FORWARD_OBJECT_ID = c2.OBJECT_ID
INNER JOIN DESIGN1.COLLECTION_ c3 ON r3.OBJECT_ID = c3.OBJECT_ID
INNER JOIN DESIGN1.REL_COMMON r4 ON r4.FORWARD_OBJECT_ID = c3.OBJECT_ID
INNER JOIN DESIGN1.COLLECTION_ c4 ON r4.OBJECT_ID = c4.OBJECT_ID
WHERE r1.FORWARD_OBJECT_ID = 60
ORDER BY c1.CAPTION_S_, c2.CAPTION_S_, c3.CAPTION_S_, c4.CAPTION_S_;

EXIT;
