SET PAGESIZE 50000
SET LINESIZE 500
SET FEEDBACK OFF
SET HEADING OFF

-- Level 0: Root
SELECT '0|0|380140|FORD_V801_OHIO|FORD_V801_OHIO|' || NVL(c.EXTERNALID_S_, '') || '|0' 
FROM DESIGN4.COLLECTION_ c
WHERE c.OBJECT_ID = 380140;

-- Level 1: Direct children
SELECT 
    '1|380140|' || c.OBJECT_ID || '|' || 
    NVL(c.CAPTION_S_, 'Unnamed') || '|' ||
    NVL(c.CAPTION_S_, 'Unnamed') || '|' ||
    NVL(c.EXTERNALID_S_, '') || '|' ||
    TO_CHAR(r.SEQ_NUMBER)
FROM DESIGN4.REL_COMMON r
INNER JOIN DESIGN4.COLLECTION_ c ON r.OBJECT_ID = c.OBJECT_ID
WHERE r.FORWARD_OBJECT_ID = 380140
ORDER BY r.SEQ_NUMBER
FETCH FIRST 10 ROWS ONLY;

EXIT;