-- Siemens Tecnomatix Tablespace Creation
-- Matches the DBCA template: dbca_EMSDB12_12201_win.dbt
-- Run as SYS with SYSDBA privileges

-- PP_DATA tablespaces (uniform extent allocation)
CREATE TABLESPACE PP_DATA_128K
  DATAFILE 'F:\Oracle\oradata\localdb01\PP_DATA_128K_01.DBF'
  SIZE 200M REUSE AUTOEXTEND ON NEXT 20M MAXSIZE 32767M
  EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K
  SEGMENT SPACE MANAGEMENT AUTO
  LOGGING;

CREATE TABLESPACE PP_DATA_1M
  DATAFILE 'F:\Oracle\oradata\localdb01\PP_DATA_1M_01.DBF'
  SIZE 300M REUSE AUTOEXTEND ON NEXT 30M MAXSIZE 32767M
  EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
  SEGMENT SPACE MANAGEMENT AUTO
  LOGGING;

CREATE TABLESPACE PP_DATA_10M
  DATAFILE 'F:\Oracle\oradata\localdb01\PP_DATA_10M_01.DBF'
  SIZE 500M REUSE AUTOEXTEND ON NEXT 100M MAXSIZE 32767M
  EXTENT MANAGEMENT LOCAL UNIFORM SIZE 10M
  SEGMENT SPACE MANAGEMENT AUTO
  LOGGING;

-- PP_INDEX tablespaces (uniform extent allocation)
CREATE TABLESPACE PP_INDEX_128K
  DATAFILE 'F:\Oracle\oradata\localdb01\PP_INDEX_128K_01.DBF'
  SIZE 200M REUSE AUTOEXTEND ON NEXT 20M MAXSIZE 32767M
  EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K
  SEGMENT SPACE MANAGEMENT AUTO
  LOGGING;

CREATE TABLESPACE PP_INDEX_1M
  DATAFILE 'F:\Oracle\oradata\localdb01\PP_INDEX_1M_01.DBF'
  SIZE 300M REUSE AUTOEXTEND ON NEXT 30M MAXSIZE 32767M
  EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
  SEGMENT SPACE MANAGEMENT AUTO
  LOGGING;

CREATE TABLESPACE PP_INDEX_10M
  DATAFILE 'F:\Oracle\oradata\localdb01\PP_INDEX_10M_01.DBF'
  SIZE 500M REUSE AUTOEXTEND ON NEXT 100M MAXSIZE 32767M
  EXTENT MANAGEMENT LOCAL UNIFORM SIZE 10M
  SEGMENT SPACE MANAGEMENT AUTO
  LOGGING;

-- AQ_DATA tablespace (Advanced Queuing)
CREATE TABLESPACE AQ_DATA
  DATAFILE 'F:\Oracle\oradata\localdb01\AQ01.DBF'
  SIZE 200M REUSE AUTOEXTEND ON NEXT 20M MAXSIZE 32767M
  EXTENT MANAGEMENT LOCAL UNIFORM SIZE 128K
  SEGMENT SPACE MANAGEMENT AUTO
  LOGGING;

-- PERFSTAT_DATA tablespace (Performance statistics)
CREATE TABLESPACE PERFSTAT_DATA
  DATAFILE 'F:\Oracle\oradata\localdb01\PERFSTAT_DATA_01.DBF'
  SIZE 200M REUSE AUTOEXTEND ON NEXT 20M MAXSIZE 32767M
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE
  SEGMENT SPACE MANAGEMENT AUTO
  LOGGING;

-- Create Data Pump directory for imports
CREATE OR REPLACE DIRECTORY DUMP_DIR AS 'F:\Oracle\admin\dump';
GRANT READ, WRITE ON DIRECTORY DUMP_DIR TO SYSTEM;

-- Verify tablespace creation
SELECT tablespace_name, status, contents, extent_management
FROM dba_tablespaces
WHERE tablespace_name LIKE 'PP_%'
   OR tablespace_name IN ('AQ_DATA', 'PERFSTAT_DATA')
ORDER BY tablespace_name;

EXIT;
